EDCD/EDMarketConnector

- edsm.py
EDSM api is now returning "[]" instead of "-1" when the system name doesn't exist in its database. Fixes "Can't connect to EDSM" errors when jumping to a new system.
> Fix crash when system isn't already known to EDSM

- requirements
To make development easier on others, requirements freezes the dependancies for edmc and then someone else can use ` pip install -r requirements`
> Add requirements file for use with pip

- edshipyard.py
When refreshing data at a station, I got an error that the global variable querytime was not defined.
It looks like querytime should be defined a few lines further down than it actually was, because where it was it didn't do anything. Everything worked fine after this fix.
> Fix a bug in edshipyard.py

- L10n/cs.strings
Could not find this translation in OneSkyApp, so I did it this way.
> Fix of Czech translation of "Transparent"

- README.md
Someone managed to slightly badly set the config such that the program wouldn't run, so needed to know where to look to delete/edit it. This wasn't documented in README.md (where this patch adds it) or on the wiki.
> Document where configuration is stored

- EDMarketConnector.py
This allows manipulation of the main window by window managers & desktop
environments that can create rules based on window names/classes.
E.g., I have everything tiled by default so starting EDMC sizes it to the
entire space of my monitor. With this change, I can specify that the EDMC
window should be started as a floating window.
```bash
$ echo "WM_CLASS(STRING) = \"NAME\", \"CLASS\"" && xprop | grep "WM_CLASS"
WM_CLASS(STRING) = "NAME", "CLASS"
WM_CLASS(STRING) = "edmarketconnector", "Edmarketconnector"
```
> Set the WM_CLASS Name of the Root Window

- plugins/eddn.py
I was surprised to see errors from plugins/eddn.py during python3 porting when I thought I'd disabled the option in settings at the start of this work.  It turns out the check in the code was just whether config.OUT_MKT_EDDN was True, rather than if that option was currently set.
> eddn cmdr_data not actually checking 'send to EDDN' option.

- EDMarketConnector.py
- config.py
- setup.py
* Re-uses the 'About {APP}' that was defined because the MacOS version
always had an 'About' bit.
* As a side effect of wanting the copyright string in the popup this is
now defined in config.py, and setup.py has been adjusted to also take
it from there.
* The About popup includes a link to the release notes, contingent on
the git tag existing on github.
* Only one instance of the popup is allowed at once.
* There's still a 'TODO' for moving 'Check for updates' into this
popup.
Closes #509
> Implements 'Help > About' menu item

- EDMarketConnector.wxs
- docs/Translations.md
This both fixes the new 'sl' and 'sr-Latin-BA' strings files to be included in a new install *and* documents the necessary steps to do so in docs/Translations.md.
closes #547
> Add the new languages to the installed files.

- EDMC.py
- monitor.py
A user accidentally copied a Journal file into the same directory, resulting in
a "Journal.<datetime>.<serial> - Copy.log" file.  EDMC 3.99.0.0 then picked this
up and re-sent events to EDDN, EDSM, Inara.
So, let's be strict about the filenames we consider to be valid, live, Journal
files.
* Journal files have one basic form: Journal.YYMMDDHHMMSS.XX.log
* In addition the word 'Beta' can be inserted just after 'Journal'
So regex '^Journal(Beta)?\.[0-9]{12}\.[0-9]{2}\.log$' matches both and nothing
else.
Test: The "copy to same directory" that originally triggered this.  EDMC no
longer 'sees' the copy.
Test: Copied a Journal file out, renamed it to later date/time, copied that
back in.  EDMC saw it correctly as a new file.
NB: Didn't test the "no emitter" version at monitor.py:251, but no …
> Use a strict regex for matching Journal*.log files

- theme.py
The added exception at least means we don't then segmentation fault in
the next line, but it also means we then hit another exception later
in the main loop as we try to create the main Tk window.
Hopefully the exception messages will be clear enough to the user.
closes #500
> theme.py: Check if we can actually get an Xorg/X11 display

- config.py
* When I changed 'company_name' in setup.py to 'EDCD' this caused WinSparkle to
store, and look for, its keys there.
* There's code in config.py that attempts to set some WinSparkle options, only
if they weren't already there.  This is hardcoded to use the old 'Marginal'
Registry Key.
So, explicitly do this WinSparkle setup under 'EDCD', and *always* set the
update_interval value to match what we expect.  Leave the 'CheckForUpdates'
under the 'is it already here?' check so that we respect the user's choice.
> Fix WinSparkle options to be under EDCD key

- EDMC.py
* I neglected to `import re` when I changed the Journal file name check.
* `map` isn't comparable in Python 3.7, need to `list()` it as well.
* Just print the full `appversion`.  The old code was assuming that none of
A, B, C, D in A.B.C.D would be two or more digits.
close #566
> EDMC.py: import re, fix version compare and report

- EDMC.py
- theme.py
EDMC.py would break due to an import chain that ends up in theme. Theme
does a whole bunch of work to setup our GUI for EDMarketConnector.py,
but it does this on any import, which will fail spectacularly if there
is either no DISPLAY var set or no X11 libs available on our machine at
all (as a sidenote this means it probably also breaks on a wholly
wayland install).
This fixes the issue by adding a check for an environment variable on
import of theme. This can and WILL break if the env var is set and
EDMarketConnector.py is used, but if you do that its your own fault.
> Fix #568 with ENV var workaround

- commodity.py
- plugins/eddn.py
- td.py
The UI for setting the 'anonymous' option was removed in
f17f5d3f257e2359d4728ce8c296d70dc5e7609f ("PKCE OAuth2 access to cAPI").
Since then there's been no way for a user to set, or unset, this option
(and the associated custom uploaderID).  However anyone with the registry keys
still set would have had them take effect.
This commit removes the last bits of code that were making use of it.
Note that the EDDN Relay anonymises all uploaderID values, so no listener
has been seeing the 'raw' values for a long time now.
close #575
> Remove all use of defunct 'anonymous' option

- plugins/inara.py
This works by checking on _any_ event the status of the cargo vs the
current stored version. If the live cargo differs from the updated
cargo, _and_ we have not sent any update in the past 45 seconds (as this
would have contained the cargo anyway), we queue an actual send to the
API.
This unfortunately isn't checked only when docked, but on the plus side
miners will be happy to have their cargo updated relatively often.
Fixes #477. Possibly not quite what they wanted, but its about as close
as this will get
> Fixed updating inara cargo only on major events

- plug.py
This is already done for 'found' plugins, so let's avoid any potnetial
future surprise with the internal ones as well.
close #589
> sort internal plugins before loading

- EDMC.py
I got too enthusiastic in 3ff77c3c54dea4bf36d957cd2dbd5b1b02dcb094 when
I removed the "cut it down to A.BC" code.  This restores the old output,
but using a less confusing if/else.
close #604
> Restore 'EDMC -v' to announcing newer versions.

- monitor.py
Doing so causes the ShipType to not be used in the UI, so you get a
'link' with just a space for the text.
Any user who purposefully sets their ship's name to a single space
can live with seeing the model name instead.  Yes, I checked, the game
allows it.
> monitor.py: Don't record '' or ' ' as ShipName

- .gitignore
Just to ensure that they're not reported by any local tools (like vscode, which keeps telling me I have 1k untracked files)
> ignore editor and virtual enviroment directories

- monitor.py
Ensures that journal_dir is always at least an empty string.
Fixes #639
> Dont crash when journal_dir is None

- plugins/inara.py
This adds a new thread that will run in a loop sending inara events once
ever 30 seconds. The old method of sending once for "special" events has
been removed.
**THIS IS UNTESTED** it needs testing before it is merged
> Switched to using a timer for inara updates

- .github/workflows/push-and-pr-checks.yml
This doubles up the work the annotate workflow does, but should always work, unlike the annotations and fork PRs.
> Run flake8 for status on all pull requests

- EDMCLogging.py
- EDMarketConnector.py
- plug.py
1. Log messages propagate up Parent.Child chains, so we don't need a channel on the plugin logger.
1. But it still needs the filter to define qualname and class for formatting.
> Ensure 'found' plugins have correct logging from core code

- PLUGINS.md
- plugins/inara.py
- timeout_session.py
timeout_session provides two things, TimeoutAdapter, a HTTP adapter subclass that automatically adds timeouts to all requests, and new_session, which automatically creates a request.Session with the adapter in the correct place.
inara.py now uses a timeout_session instead of a direct reqests.Session
> Fix request hangs threads on exit

- .pyproject.toml
- pyproject.toml
- requirements-dev.txt
[isort](https://pypi.org/project/isort/5.3.0/) is an automated import sorter, which by default orders similarly to pycharm (stdlib grouped, then third party, then first party, with spaces between). `flake8-isort` is a flake8 plugin that leverages isort to provide warning level lint messages.
The options added are for hanging grouped indent on multiple lines: 
```py
from xxx import (
a, b, c, d, e, f, g
h, i, j, k, # and so on
)
```
and for the line length limit to 119 (120 makes autopep8 argue with it)
This PR also renames `.pyproject.toml` to `pyproject.toml`, as that is the *correct* name as listed in [PEP 518](https://www.python.org/dev/peps/pep-0518/)
> Add flake8-isort for import order

- plugins/inara.py
This replaces the list+queue system that the inara plugin originally
used with a deque based one.
The main differences here are that the list the worker thread uses to
send to inara and the list that events are added to is the same, with
the worker thread making a duplicate and clearing the original each time
it sends events (losing events if it fails to upload three times).
The format of the data has changed as well, from simple tuples to
NamedTuple classes that provide some extra type safety and sanity when
accessing fields.
The event queue itself is actually multiple queues, one per
API/FID/CMDR_name triplicate, thus allowing multiple commander switches
while we're running without causing any weird issues
> Rewrote inara queue system

- plugins/eddb.py
- plugins/edsm.py
- plugins/inara.py
FSDTarget contains the target system under `SystemAddress`, meaning that
any time you selected a star other than the current one, plugins'
`this.system_address` was updated to that target, rather than the
current system. Said updating causes the links provided from system_url
to reflect that update (for providers that support ID64s).
This changes the journal_entry behaviour to only update
`this.system_address` when the event is any of Location, Docked,
or FSDJump, all of which contain only the current system.
> Fixed system link updating on FSDTarget

- EDMarketConnector.py
If anything does `import logging` it's likely to grab a copy of sys.stderr before we redirect it meaning things aren't properly redirected when we start logging.
So put the redirect as early as possible in EDMarketConnector.py.
This will need a test implemented to be sure it's not accidentally broken by addition of an import before this.
> Logging: Move stdout/stderr redirect to before `logging` can be run

- EDMarketConnector.py
- prefs.py
There'll be more cleanup that can be done as a consequence of this.  Other places that want a file/directory dialogue, and all of the ctypes stuff that sets things up.
But for now let's just do this and test it.
> Use tkinter.filedialog on win32, because we now fix locale encoding

- EDMCLogging.py
This should have been changed when the rotating file logging was implemented.
> Plugin logging needs to be DEBUG, to let channels decide later.

- companion.py
- plugins/eddn.py
Out of paranoia we're also checking if it's a non-empty list and logging that as an error if encountered.  It should be a dictionary!
I'll check if the ships code should also be this paranoid.
> Catch where station modules from CAPI is an empty list.

- EDMarketConnector.manifest
Given the workaround we found for #711 talks about applications that are NOT unicode aware I looked into how to tell Windows that you *are*.
This small change should do that.
> Attempt to select UTF-8 code page in manifest.

- EDMC.manifest
- EDMC.py
- EDMCLogging.py
- companion.py
- plug.py
- prefs.py
- setup.py
This should be both executables now using UTF-8 codepage by default.
* Also adds start DEBUG logging to EDMC.py (after --loglevel is handled).
* Tweaks the way non-main modules get a logger, use EDMCLogging.get_main_logger() as it will handle telling the difference between EDMarketConnector and EDMC.
* Tweaks the pluging logger creation in plug.py so it's ready in case EDMC.py starts loading plugins.
> Use manifests for UTF-8, including in EDMC.py

- plugins/eddn.py
Fleet Carriers can easily go from having some sell/buy orders to having none.  Thus we *do* need to send empty commodities lists if that's what we see, so that EDDB and the like can update properly.
We then catch the specific error so as to reduce logging/exception output.
> Send empty market data over EDDN

- EDMC.py
not (A or B) != not A or B
Although "not A and not B" would be equivalent.
> EDMC: Revert accidental change of boolean logic

- prefs.py
As we can't rely on the is_wine check, use an exception for this.
> try/except ctypes.windll.user32.CalculatePopupWindowPosition

- setup.py
I know there are some f-strings that can be rf-strings to save doubling \\ in `os.execute(..)` commands.
> Further setup.py cleanup

- .pre-commit-config.yaml
- EDMarketConnector.py
The main aim here is to get it passing my pre-commit hooks, so flake8 and mypy primarily.
I'm leaving TODO's behind on some things for later cleanup.
> Cleanup of EDMarketConnector.py

- EDMCLogging.py
Relatively simple. Because all of our loggers are created out of
EDMCLogging, we can create a fake type in EDMCLogging that inherits
from logging.Logger but also defines a trace method.
Once that is done, we just have to annotate our methods to get loggers
with the new type, cast all of the returns, and suddenly we no longer
have any complaints about logger.trace. This doesn't _actually_ change
any behaviour at runtime, and logging.Logger.trace and logging.TRACE
will continue to be broken, but those are used far less than
logger.trace is used throughout the codebase, and therefore I think we
can live with `# type: ignore` comments everywhere
> Added type checker magic to make TRACE work

- companion.py
* The companion Session.query is called for *all* CAPI endpoints and
only the /profile one will return lastStartport data, which is where
ships/modules are if present, so only do these checks if we see
lastStarport.
> CAPIData: Only call self.check_modules_ships() if lastStarport present

- EDMCLogging.py
- EDMarketConnector.py
Python name mangling is more about name collisions than actually making
things private.
This commit adds a check to resolve mangled names to their runtime
names, and adds a just-in-case default to fetching the attribute.
Fixes #764
> Added name mangling support to EDMCContextFilter

- EDMC.py
ED always writes its files as utf-8 it seems, this ensures that we always try to read them as such.
Fixes #779
> Always read journal with utf-8 in EDMC.py

- EDMCLogging.py
- EDMarketConnector.py
- docs/Releasing.md
- requirements-dev.txt
* Change to show 'Shutting down' on exit, rather than withdrawing the UI straight away.  Should make it more obvious if the process hangs during shutdown.
* Likewise add a pop-up if the program is detected as already running at startup, instead of exiting silently.
* Fix for mangled names support in our logging.
* py2exe now from PyPi (paving the way for GitHub builds).
> Cherry-pick in some key commits for upcoming 4.1.5

- .github/workflows/windows-build.yml
This can be invoked manually or on pushes to tags matching v*, which may or may not actually behave as expected. If GA takes the workflow version etc from that tag, it should work fine. Otherwise py versions may cause it to fail.
> Build automatically with github actions

- EDMCLogging.py
Maybe with this we'll see something 'here' or later to give a clue as to why this doesn't work on at least two systems.
> EDMCLogging: Catch inspect.getframeinfo(frame) not working

- EDMCLogging.py
- EDMarketConnector.py
This is some best effort support for using logging in properties.
This works by using the (as suggested by reporter) inspect
`getattr_static` method, and failing that (as it can possibly fail),
wrapping a `getattr` in a try/catch for a RecursionError--don't want to
catch other things, probably best if that explodes on its own.
From there as the `property` object will not have location information,
we rebuild as best we can to an approximation of what the path would be.
With a healthy dash of defensive programming "Just in case".
I don't think that this will have any adverse effects to other logging
methods, as all the new code should only be touched if we hit a property
object.
Closes #808
> Added support for logging from properties

- EDMarketConnector - reset-ui.bat
- EDMarketConnector.py
- L10n/en.template
- prefs.py
This is distinct from the windows only transparent theme, I wanted to enable that on other platforms too but could not find a way.
The way this works is it changes the transparency of the entire EDMC window. Tested on windows and linux, works as expected for both.
> Add multi platform transparency

- EDMarketConnector.py
- docs/Killswitches.md
- killswitch.py
- plugins/eddb.py
- plugins/eddn.py
- plugins/edsm.py
- plugins/inara.py
Killswitch exists to allow us to disable features causing issues in
specific versions remotely.
The system is designed to support plugins, where they can request their
own killswitch list by querying any web file that follows our format
(docs to be added), and using the returned KillSwitchSet to check for
disabled features.
> Added killswitch library

- EDMarketConnector.py
- dashboard.py
- monitor.py
- plug.py
See #834 - we need to be better about ceasing journal parsing during application shutdown.
This might go on to also re-ordering the shutdown sequence.
> Bail out of Journal monitoring during shutdown

- EDMCLogging.py
#766 didn't completely fix #764, unfortunately: logging from mangled methods inside classes whose names started with an underscore is still broken (it no longer crashes, just fails to determine the name). This PR fixes that.
Python's name-mangling rules are _weird_:
```python
class Foo:
def method(self): pass
def __mangled_method(self): pass
class _Foo:
def method(self): pass
def __mangled_method(self): pass
class ___:
def method(self): pass
def __mangled_method(self): pass
for cls in [Foo, _Foo, ___]:
print(cls.__name__, [attr for attr in dir(cls()) if "method" in attr])
```
```console
$ python3 test.py
Foo ['_Foo__mangled_method', 'method']
_Foo ['_Foo__mangled_method', 'method']
___ ['__mangled_method', 'method']
```
This PR is still arguably incomplete, because it incorrectly applies …
> Fix logging from mangled methods where class name starts with "_"

- EDMarketConnector.py
- config.py
- dashboard.py
- hotkey.py
- monitor.py
- plug.py
- plugins/edsm.py
- plugins/inara.py
- prefs.py
- protocol.py
- update.py
1. Adds a Config class member and helper functions to set and check for shutdown.
2. Sets this flag at the top of AppWindow.onexit().
3. Checks the flag so far only in plug.py show_error().
Still needs a further look into where else calls event_generate() and should have the check.
> Avoid Tk event_generate() calls during shutdown.

- EDMarketConnector.py
- config.py
- constants.py
- protocol.py
1. We were now importing from config before the console redirect code
runs.
2. That means that config.py's `logger = logging.getLogger(appname)` caused the logger to be set up whilst stdout/err were still pointing at the console.
3. So the redirect then had no effect on logging output.
This commit moves the import from config (and also killswitch, because it also imports logging) to after the *moved* console redirect code.
NB: This needs the "detected a process already running" instance checking.
NB: There's still a `True or ` for testing purposes EDMarketConnector.py:25
> Fix console redirect to work with config.py now using logging.

- EDMarketConnector.py
- protocol.py
So as to actually allow `runas` this changes the win32 "Is there any window with the expected handle already?" check into a lock on a file in the `journals_dir` instead.
This also means that we can actually enforce this on all platforms.  win32 doesn't have fcntl so we use msvcrt there, but we assume (with a try/except) that all other platforms will have fcntl.  Worst case scenario they're in the same situation as before, no check at all for more than one process.
NB: This is going to be tricky when forward-ported into `develop` due to absolutely needing to use config.get() to obtain the `journals_dir`.  In `develop` that will cause logging to be set up before it should.  Might have to add something to explicitly close all logging so that setting it up again later correctly follows the …
> Switch to using a journals folder lockfile to enforce single process

- EDMarketConnector.py
- config.py
- protocol.py
This then gets checked in protocol.py to force using the localhost webserver instead of edmc://auth handler.
Will address #856
> Add `--force-localserver-for-auth` CL arg to EDMarketConnector

- EDMarketConnector.py
- PLUGINS.md
- config.py
- protocol.py
This ports in various recent changes to `main`.  `develop` has diverged too much for this to be easy via a merge or rebase.
* Use a lock file in the journals_dir location to prevent more than one instance running against the same journals.  We no longer check just for a Windows handle.  So this is more correct on win32 *and* is now a thing on all other platforms.
* Adds `--suppress-dupe-process-popup` CL arg to suppress "we're a dupe!" popup to aid those using batch files to launch EDMC alongside the game.
* Two minor fixups of typos in PLUGINS.md.
* Misc noqa comments and other flake8 fixups.  We're now only missing type annotations in EDMarketConnector.py.
> Port in the journals_dir locking and other changes

- EDMarketConnector.py
- L10n/en.template
- companion.py
There's no reason to not allow Steam and EGS commanders to auth via the relevant store account, instead of needing to use the associated Frontier login credentials.
> Add Steam and EGS to Frontier Auth audiences.

- .github/workflows/windows-build.yml
- EDMarketConnector.wxs
- monitor.py
- setup.py
Also contains a config.get() -> config.get_str() change for the new references of journaldir in monitor.py that I'd just forward ported.
> Move us to Python 3.9

- PLUGINS.md
- monitor.py
Journal doc v28 is incorrect about the word for the event and file being `Route`, it is `NavRoute` (tested in-game).
We augment the `NavRoute` event with the data from the file, so plugins can just look at the event rather than needing to check monitor.state[`NavRoute`], although the data is also there for later reference.
There is **no indication** if the player clears a route (not in journal or a Status.json flag).
The format of the `Route` array data is also different from the v28 doc.
> Add support for NavRoute event and file contents.

- EDMarketConnector.py
- journal_lock.py
This way we can tell the difference between:
1. This process obtained the lock.
2. Another process has the lock.
3. We couldn't get the lock due to not being able to open the lock file read-write.
Case 3 is currently also returned if the configured journal directory doesn't exist.  This will be the case on any MacOS system that never had the game running.  Likely given the OS hasn't been supported for the game in years now.
> Change JournalLock.obtain_lock() return to an Enum.

- config.py
- journal_lock.py
- requirements.txt
1. pyobjc in requirements.txt
2. Bug with `darwin` config.delete() not respecting `suppress` argument fixed.
3. Only actually JournalLock.release_lock() if we actually hold a lock.  Enables changing Journals location from non-existent to another without a fatal exception.
There's still an issue with the whole hotkey code not working because the application needs a MacOS permission to generally monitor keyboard input.  The old way to grant this has changed in Catalina.  There's "Input Monitoring" but I can't find any way to add an arbitrary app to it.  We might need to find how to get the EDMC code to explicitly make the request so that the user can grant it.
And even then I'm not sure the current way of doing hotkeys on `darwin` is the recommended way on Catalina.  It's going to take a …
> Get MacOS working as well as we can.

- journal_lock.py
* If it's None then set journal_dir_path to None as well.  Setting '' or nothing results in '.' (CWD), which could cause other issues.
* As we do this in three places, it's in a helper function.
* New JournalLockResult.JOURNALDIR_IS_NONE to signal this.
* Fix checking of return from obtain_lock() to specifically reference JournalLockResult.ALREADY_LOCKED.
Closes #910
> JournalLock: Check for journal_dir of None 

- EDMarketConnector.py
While it isn't directly an issue in main (right now), the fix applies here forward, so we may as well do it here and not deal with a headache later.
Fixes #908
> Ensured that CAPIData objects are JSON Serialisable

- plugins/eddn.py
A damaged station has `"modules": []`, so trips over modules.values().
Being paranoid about the other data in there as well.
> plugins/eddn: Add paranoia about data in is_horizons()

- EDMarketConnector - localserver-auth.bat
- EDMarketConnector.py
- EDMarketConnector.wxs
- L10n/ko.strings
- docs/Translations.md
- setup.py
Somehow `main` never got the code to allow `edmc...` argument.
And despite adding it on OneSky we never added Korean to the build/install process.
> Allow 'edmc' argument to .exe to work (and add Korean language)

- plugins/eddn.py
self.replaylog[0] should always exist for the `json.load()`, unless the `update_idletasks()` is somehow allowing the timer to call into `sendreplay()` again.  So add a check after that, with traceback logging, to return.
See #926
> Add Paranoia check in sendreplay()

- monitor.py
1. Pick up 'JournalAlpha' files if they ever are a thing.
2. Pick up 'alpha' in gameversion to set is_beta = True.
3. For now any gameversion without 'Fleet Carriers Update' is considered a beta.
The last bit can be removed/updated as and when we know for certain what's in the Odyssey alpha game version.
> Extra paranoia about game version for forthcoming Odyssey Alpha

- companion.py
Nothing other than /shipyard actually returns the modules and ships data, so checking for it anywhere other than that automatically is just asking for extra log noise and nothing else.
>     Fix spurious modules or ships was None

- monitor.py
- plugins/eddn.py
- plugins/inara.py
* Comment out the traceback in plugins/eddn.py, the return is enough.
* 'Called with no event_queue' can be TRACE.
* Don't care about "Everything was alright, the near-neutral status just wasn't stored." from Inara.
> Reduce some log spam:

- PLUGINS.md
- README.md
- docs/Releasing.md
* Extend EDCD copyright into 2021 here as well.
* Recommend *against* any attempt at making plugins also work with Python 2.7.
* setup.py no longer writes appcast files.  Mention edmarketconnector.xml enclosure instead for the url= bit.
* DRY about location of log files, just point to appropriate wiki link.
> docs: General update for `main` now using Python 3.9 & misc

- plugins/eddn.py
The rebase of `develop` on `main` seems to have undone these by accident when I resolved one of the conflicts.
We lost all of the safe_modules_and_ships() stuff (which includes the calling functions then using the return rather than diving into the data directly themselves again).
And we lost some of the extra ships['shipyard_list'] paranoia.
> EDDN: Restore safe_modules_and_ships() from 4.2.4

- monitor.py
An old loadout might have been written before we made any attempt at
utf-8.
Even now, if someone is on sufficiently old Windows we might not be on
utf-8. If that's the case then no telling what will/won't work, but try
to read/write with utf-8 first, and fall back to default encoding if it
fails.
> Add try/except retry/paranoia to monitor.export_ship()

- monitor.py
We had a report of a UnicodeDecodeError trying to read an old file.  So try utf-8 first, if it fails try the default, and if nothing else try to write a new file so the next call should actually work as expected.
> Make export_ship() paranoid about possible encoding issues

- plugins/eddn.py
- plugins/edsm.py
- plugins/inara.py
- setup.py
- update.py
Various fixes for config.app_version() now returning `semantic_version.Version`, instead of `str`.
Checked the changes in debugger, plus built an installer and checked its .exe log file.
> Fix where config.app_version() not being a string causes issues.

- plugins/eddn.py
It seems the game can report a Scan event *after* you've jumped to another system.  So don't blindly set StarPos on Scan, check the SystemAddress against where we think we are first.
I checked, and we shouldn't need to update either of the EDSM or Inara plugins for this.
Closes #961
> EDDN: Only add missing StarPos if for current system

- EDMarketConnector.py
- PLUGINS.md
- collate.py
- companion.py
- coriolis.py
- edshipyard.py
- loadout.py
- monitor.py
- outfitting.py
- plugins/eddb.py
- plugins/eddn.py
- plugins/edsm.py
- plugins/inara.py
- shipyard.py
- stats.py
- util_ships.py
This introduces a new monitor state variable `on_foot`.
Currently this will only be true when you login at a station.  There's only `Disembark` when you get off a shuttle at one, with no new `Location`/`Docked` event to fill in the necessary data to check against CAPI data.
> Attempt to get on-foot detection working, so EDDN data sends

- EDMarketConnector.py
- monitor.py
This should get rid of the 'called with empty event_queue' logging, unless something *is* broken.
> Convert monitor.event_queue to a queue.Queue

- EDMarketConnector.py
- config.py
We need the config.py read of .gitversion to be from the right place.
However, should this actually be gated purely on frozen?  Sure, for the specific check we have right now, but we do need cwd to be correct for other things.  Plugin loading is basing it off the parent of `__file__`, and this chdir ought to do the same.
> EDMarketConnector.py: Move chdir as early as possible

- EDMarketConnector.py
Initially I was looking into why, on Alpha, you got stuck on 'Fetching data...' if hitting Update button when in a taxi.
This turned into then also tracking down why 'Last updated at: ' would disappear when logging into Alpga, quitting, and then logging into Live.
> Ensure status text not stuck when on foot

- monitor.py
ShipLocker is where items not currently with you in your BackPack are stored.
There are three categories: 'Component', 'Consumable', and 'Item'.  Those in the ShipLocker are stored directly under those names in monitor.state.  Those in the BackPack are stored as keys of monitor.state['BackPack'].
There are some assumptions about some events only interacting with ShipLocker inventory, not BackPack.  Will test this.
> Add support for all ShipLocker and BackPack related events

- plugins/inara.py
When you're on a fresh character you have no reputations yet, so avoid causing an Inara API error, including status line text.
> Inara: Don't send a setCommanderReputationMajorFaction if we have no Reputations

- EDMarketConnector.py
This is currently the case on Odyssey Alpha Phase 1 when logging in on-foot.  There's no Journal 'Loadout' event, but the CAPI update does let us know we have a Sidewinder active.  But `monitor.state['Modules']` is None.
I then applied extra paranoia to both Journal 'Loadout' processing and the CAPI retrieval of data to ensure this ttkHyperlinkLabel is always in the correct state.  So, yes, this means the shipyard provider will never be callable in this state now, but let's leave the paranoia check there anyway.
> Don't try to generate a shipyard link if we have no known loadout.

- plugins/eddn.py
This likely hadn't been tested since a rewrite due to pre-Odyssey alpha having broken CAPI without shipyard_list on normal stations.
> EDDN: Fix building of "ships this station sells" list.

- monitor.py
1. monitor: Only forget station on Disembark if not from own ship
> Any further fixups to on-foot support now we have our own ships

- PLUGINS.md
- monitor.py
This is the *one* field that wasn't always initialised.
> monitor.py: Initialise EDLogs self.systempopulation

- companion.py
We'll now actually complain if a user forgets which account is which and Frontier Auths for other than the current commander.
> companion: /decode access token and check customer_id matches FID

- EDMarketConnector.py
- config.py
- protocol.py
It's useful to have the edmc:// protocol used on Windows when debugging, if, you know, you're trying to debug the edmc:// code.
> EDMarketConnector: Add CL arg to force use of edmc:// protocol

- companion.py
This could just be the Odyssey PTS CAPI being crap... but what's been observed is the commander->docked flag not properly updating.  This then leads to companion.Session.station() thinking we're still docked when we're not.  That then has the knock-on effect of trying to use lastStarport data when we normally wouldn't in this situation.
If not docked and you've jumped to a new system the lastStarport data is mostly empty, including 'services' being an empty array, instead of the usual dictionary.
So, add paranoia checks, even if this is just PTS CAPI being crap.
> Be more paranoid about companion.Session.station() queries

- monitor.py
This addresses `ModuleRetrieve` and `ModuleStore`, but I'm reviewing other events said to have 'Cost' as well.
Closes #1026
> Be paranoid about presence of 'Cost' on some Journal events

- monitor.py
When docking in an Apex taxi the 'Docked' event has many fewer fields.  So this reworks the monitor.py handling of 'Docked' to not longer be married to the Location/FSDJump/CarrierJump handling.
> Address taxi different Docked event.

- config.py
When starting EDMC for the first time, linuxconf creates the required
file automatically but does _not_ create our config section. This causes
a keyerror on any access to config.
Simple solution, test that the section exists, if it doesnt, create it
(and backup any existing file beforehand)
> Ensure that Section exists on linuxconf

- EDMCLogging.py
- tests/EDMCLogging.py/test_logging_classvar.py
Logging being from a global "class definition" function means no `__qualname__` on the function object we find.  So just use `name`.  The `module` bit should take care of the entire thing otherwise being what we want.  Certainly better than *nothing* for `%(qualname)s`.
> EDMCLogging: No fn.__qualname__ ?  Just use `name`.

- monitor.py
- plugins/eddn.py
This is so listeners can make decision on if/how/when to store data that might be from base/horizons or Odyssey.
> plugins/eddn: Send bool 'odyssey' in all event messages.

- prefs.py
The code around the dropdown menu in prefs for shipyard providers was a
bit too clever for its own good.
This brings it in line with the behaviour of the other two
> Fixed showing unset shipyard provider as False

- PLUGINS.md
- monitor.py
- plugins/edsm.py
* Surprise!  The new event is `BackPack`, not `Backpack`, although the filename *is* `Backpack.json`.
* Store the loaded JSON dict in `monitor.state['BackpackJSON']`.  That `p` is lower case to match with the filename, not the event name.
* Document this in PLUGINS.md.
Unless EDSM is telling us to discard this we should now be sending it.
> Fix BackPack event support to actually work.

- EDMarketConnector.py
- monitor.py
And also change the displayed suit "type (loadout)" in reaction to journal events.
I *think* things are now working as best they can in abscence of CAPI data, and we should always use these journal events anyway.
> Ensure UI 'Suit' line is shown when it should be, and not otherwise

- EDMarketConnector.py
- PLUGINS.md
- config.py
- edmc_data.py
- monitor.py
The aim here is to use the well-localised CAPI-sourced names whenever we can.
Further work in this branch/PR will look at constructing a lookup table/regex to map the symbolic names to **English** readable names.
> Suits: Ensure a succinct and sane name for Suits in UI

- EDMarketConnector.py
- companion.py
I failed to ensure we were also doing this for the CAPI-sourced data.  If you login in-ship, and never change loadout or go on foot, it will stay showing as '<Unknown>' (which it starts as correctly, as without CAPI data if you're only in ship there's no Journal events for suits either).
> Suits: Set edmcName in suits from CAPI, and ensure displayed

- monitor.py
- plugins/inara.py
To Do:
- I believe everything we want is done here.
- I dont think there are any actual updates we can do here?
- This SHOULD be done, it currently only sends on ShipLockerMaterials as thats the only time we can be sure data is correct.
Do **BEFORE** merging
Closes #1127
> Update INARA plugin to support new odyssey API endpoints

- plugins/inara.py
The generic one interferes with more specific such events, i.e. from Journal `Location` event, if sent in the same batch.
But that means ensuring we send for *all* the actual Journal "changed location" events.
> inara: Don't send a generic setCommanderTravelLocation - be specific

- EDMarketConnector.py
- companion.py
ConnectionErrors are expected and not something we can fix. The
exception handler that was catching these previously is a catchall
intended to stop EDMC as a whole from crashing from something
unexpected.
Closes #1082
> Don't spam a stacktrace on requests.ConnectionError

- EDMarketConnector.py
- companion.py
This is obviously quite annoying but should provide a magic fix to any
user with weird auth trouble (such as those seen by
EDCD/EDMarketConnector#1166 )
Closes EDCD/EDMarketConnector#890
> Added CL arg to forget all frontier tokens

- EDMarketConnector.py
- L10n/en.template
- companion.py
- scripts/find_localised_strings.py
Should now correctly:
1. Use the 'above' comment *only* if there's no `_(...)` call on that above line, by virtue of only checking for a standalone comment on that above line.
2. Properly complain if there's an above comment, but it's for its own line, and there's no LANG comment on this line.
3. Still use own-line LANG comments if present, in preference to an above one.
> LANG comments: Fix script for all situations

- .github/workflows/windows-build.yml
- docs/Automatic Builds.md
Waits until after normal build is completed, then hashes the MSI, creates a new draft release, and uploads both the msi and the hashes file
> Automatically create releases with github actions

- Contributing.md
- EDMarketConnector.py
- config.py
- monitor.py
- plugins/edsm.py
This is aimed at addressing #1134 .
To start with it's adding some logging, including the new EDMarketConnector.exe `--trace-on ...` CL arg for activating specific TRACE logging.
> Investigate & fix wrong-commander EDSM data

- docs/Automatic Builds.md
- docs/Releasing.md
We now prefer automatic builds, triggered off our normal `Release/<semantic version>` tags being pushed.
> Docs: Update Releasing.md and Automatic-Builds.md for using auto-builds

- monitor.py
This is necessary so as to see the same instance of config.trace_on as is set up by EDMarketConnector.py.
I've not actually tested this in-game, but debugger showed monitor.py as seeing the same conf_module.trace_on as confirmed parsed in EDMarketConnector.py.
> monitor.py: Access trace_on via whole-config import

- Contributing.md
- EDMCLogging.py
- EDMarketConnector.py
- monitor.py
- plugins/edsm.py
This adds a `trace_if` method to loggers that does the same as checking for trace-on contents, however, it _also_ logs all messages that otherwise wouldnt be logged to a new `trace-all` log level, below trace, which can be activated using --trace-all
closes #1237
> Add helper methods around trace-on and override options

- PLUGINS.md
Maybe I should throw out at all from `state` table keys, that I know for sure will never appear with any meaningful values in CQC.
Also will be needed to correct first version EDMC where `journal_entry_cqc` is present now I stated it as `5.1.3+`.
> PLUGINS.md: update for `journal_entry_cqc`

- plugins/inara.py
Idea from #1239 
Since inara plugin produce very huge trace entries and now debug EDMC log is writings at trace level by default, it will be helpful to hide inara plugin's trace messages.
> inara.py: put events trace logging under `inara-events` trace_on option

- EDMarketConnector.py
- companion.py
- config.py
Closes #1096 
This PR adds CL arg for EDMarketConnector.py `--capi-pretend-down`, using this arg will make any request to CAPI raise `companion.ServerError` as if CAPI indeed down.
Also it will require add new phrase to translations but now I just want to get feedback about implemnation if all is ok then I'll add translation.
> Add CL arg `--capi-pretend-down` in order to pretend that CAPI is down

- docs/Killswitches.md
- docs/Releasing.md
- killswitch.py
- plugins/eddb.py
- plugins/eddn.py
- plugins/edsm.py
- plugins/inara.py
- scripts/killswitch_test.py
- tests/killswitch.py/test_apply.py
- tests/killswitch.py/test_killswitch.py
This PR adds the ability for killswitches to simply modify data either before or after processing to prevent data leakage.
Fields can be deleted, redacted (set to the string "REDACTED") or directly set with values given. 
If a killswitch has any kind of action, it will be attempted, and if it succeeds, the event processing with continue with modified data. Thus a simple killswitch with no additional rules simply blocks processing entirely.
> Extend killswitch functionality to fields within events

- PLUGINS.md
Using game_running() as documented yields `ImportError: cannot import name 'game_running' from 'monitor'`.  Update PLUGINS.md with the correct syntax.
Discord discussion: https://discord.com/channels/164411426939600896/726419472772235306/879787636284338306
> Fix game_running() doc in PLUGINS.md

- config.py
The ERROR log level is needlessly high for complaining about git not being installed, especially when running from an extracted source archive rather than a repo. Let's keep things calm and avoid polluting desktop session logs. The INFO log level is plenty.
> Log git's absence at the INFO level, not ERROR

- EDMarketConnector.py
- config.py
- plugins/eddn.py
We sometimes need to test against, e.g. beta.eddn.edcd.io:4431 instead, so make that easy.
Closes #1281
> Add support for --eddn-url CL arg

- EDMarketConnector.py
- companion.py
- config.py
- monitor.py
The threaded CAPI refactor erroneously caused "CAPI server says Unauthorized" to always request a **full** re-auth, not use of the Refresh Token.
This should fix that.
Closes #1330
> CAPI: Fix not utilising Refresh Token

- companion.py
It turns out this was just the blind `self.dump(r)` causing a bare exception splat, and then the status line error.  So, initialise `r` to `None` and check it isn't still that before the dump.  Also, explicitly logs the exception now.
Closes #1132
> CAPI: Don't blindly dump r(equest.Response) on failure

- L10n/en.template
- plugins/eddn.py
* Closes #1342 - A user had a NavRoute message with no Route array.  It's always from the file, so the file had to be missing it?
* This results in an EDDN '400', and now we'll drop such messages from the replaylog so they're not constantly retried.
> EDDN: Sanity check NavRoute contents & handle EDDN 400

- EDMarketConnector.py
- prefs.py
- requirements.txt
- setup.py
I finally got around to uncommenting all the infi.systray code.  It works with the py2exe we're now using.  I also made it actually minimise **to** the  system tray, if that option is active.  Before the tweak the taskbar icon would still show.
Closes #126
> Fully implement systray, and minimising to it.

- monitor.py
The order of Journal events changed from:
1. LoadGame
2. Rank
3. Progress
to:
1. Rank
2. Progress
3. LoadGame
in Odyssey, and in at least current 'base game' and Horizons clients as
well.  Also 'Reputation' event is before 'LoadGame' now.  So simply
allow those events to have populated the data, don't re-init on
LoadGame.
Yes, I'm preferring to leave the lines in, but commented, so it's clear
why those aren't being init'd, *and* why 'Statistics' still is, and as
of what game version.
> monitor: Don't re-init Enginers/Rank/Reputation on LoadGame

- companion.py
- config.py
- plugins/eddn.py
- plugins/edsm.py
- timeout_session.py
This was initially going to be just for EDDN, but then I decided to ensure we were doing this for any other requests sessions, and then it made sense to centralise it to just config.user_agent rather than setting the same thing in multiple places.  Also time_session now always sets this.
I've done a basic "run it, check no errors logged, hit 'Update' for EDDN sends" check.
Closes #1324
> Set a custom User-Agent header everywhere

- plugins/inara.py
Due to the existing code waiting for a `Cargo` event, in order to ensure batching of startup/login events, and there being no such event when logging in on foot, this message was never being sent when (re)logging in on foot.  You *had* to relog whilst in your ship in order to trigger it.
As we now have a nice timed queue for sending events, just queue this up when we see a `Rank` Journal event.  Docs state this is only at startup, so we don't need to worry about it occurring mid-session due to a rank-up (that's a `Progress` event instead) and spamming Inara.
Closing #1378
> Inara: send setCommanderRankPilot message when on-foot

- Contributing.md
- plugins/coriolis.py
- plugins/eddb.py
- plugins/eddn.py
- plugins/edsm.py
- plugins/edsy.py
- plugins/inara.py
- setup.py
Due to only being referenced in the dynamically loaded `plugins/eddn.py` there was no way for `py2exe` to know to include this.
Closing #1423
> Ensure `util/text.py` is included in Windows build/installer

- plugins/eddn.py
I still can't explicitly explain what causes these errors. All my example events have all the correct data.  So this turned into tracing the code and adding some more paranoid checks and logging.
Closing #1393
> eddn: Address EDDN server complains about some codexentry messages

- plugins/eddn.py
It *really* shouldn't ever happen, and we'll want to see the full event if it does somehow.
> eddn: Log if a 'location' event doesn't have SystemAddress

- plugins/inara.py
Doing so from 'Rank' means the 'Progress' event hadn't happened yet, so of course we only ever sent all zeroes for progress.
NB: Journal-v32 doc makes *no guarantee* about the order of the events.  Is it worth trying to be paranoid about that ?  For a 100% new player everything would be "all zeroes", so we would likely need to tweak things to store `None` as default values, and check for such.
> Inara: Trigger off 'Progress' for sending setCommanderRankPilot

- plugins/inara.py
CAPI only has the Cmdr wallet value (and loan if applicable), without anything for 'total assets'.  If we send Inara setCommanderCredits without `commanderAssets` then Inara makes a bad judgement on it and sets an incorrect total assets value.
Also:
> Do NOT set credits/assets unless you are absolutely sure they are correct. The journals currently doesn't contain crew wage cuts, so credit gains are very probably off for most of the players. Also, please, do not send each minor credits change, as it will spam player's credits log with unusable data and they won't be most likely very happy about it. It may be good to set credits just on the session start, session end and on the big changes or in hourly intervals.
So, let's just not.
Closing #1401
> Inara: Do not update credits from CAPI data

- monitor.py
We pass `monitor.system` in to `journal_entry()` anyway, so it doesn't need to be separately in the passed `state`.
> monitor: Revert state['StarSystem'] addition, it's not needed.

- plugins/eddn.py
`ApproachSettlement` semantics aren't quite so simple as we naively thought.
This PR addresses a bug in Horizons which can cause missing Lat/Long in the event.  We need to *not* send to EDDN in that case.
Closing #1476
> EDDN: Handle ApproachSettlement missing planetary coords

- theme.py
This adds a try/except around a bunch of .configure() calls on widgets. Yes, sure, this could then leave the widget in question in a broken state,but at least our entire UI won't fall flat on its face.
There may well be other places we should add such guards.  We should check for such before merging this.
If only we had plugins running in their own process with IPC for all UI poking, eh ?
Closing #1479
> Attempt to prevent plugin widget issues from bringing down whole UI

- plugins/eddn.py
It turns out some of the other strings, that do not have minLength=1 in the schema, can be empty and that's OK.   i.e. NearestDestination.
So, let's only check for the actual minLength=1 things.  Which is a few top-level key:values, and then the contents of the Traits array.
Close #1481
> EDDN: codexentry/1: Tighten up 'empty string' checks

- EDMC.py
- EDMarketConnector.py
- monitor.py
This mostly is closing #1511 , but at the same time I've fixed a few niggles:
* Old use of thread `setDaemon()` which is deprecated.
* Fix monitor.py type for variable taking the return from `journal_newest_filename()` as python was guessing badly.
* Make `journal_newest_filename()` correctly handle an input of `None`.
* Quieten the navroute retry from INFO to DEBUG to make EDMC.py less spammy if there's a NavRoute event.
> Address EDMC.py journal name fallout & misc fixes

- EDMC.py
So that, e.g. Trade Computer Extensions, can be properly informed about why things aren't working.
> EDMC: Use specific sys.exit codes, not a generic one

- plugins/eddn.py
After some investigation it turns out we can never know the body an orbital station is orbiting, so if we drop out at such, clear the tracked body information.
Closes #1522
> eddn: Clear bodyname/id on supercruiseexit, if at orbital station

- requirements-dev.txt
- setup.py
Whilst the actual `py2exe` build process now works with this workaround and latest `setuptools`, we're now hitting another issue with `infi.systray`'s use of `pkg_resources`, see https://github.com/py2exe/py2exe/issues/139
> Move back to latest `setuptools`, with workaround

- PLUGINS.md
- monitor.py
- plugins/eddn.py
If the `NavRoute.json` contains a `NavClearRoute` event, then simply consider that a success and discontinue loading attempts.
Closes #1634
> Handle NavRouteClear

- plugins/inara.py
At least 'Ancient Ruins' generate an `ApproachSettlement` event without a `MarketID` in the event.  Not even a key with `null` value.
> inara: ApproachSettlement: Only set marketID if present in event

- l10n.py
As per 3.10.6's https://docs.python.org/3/library/locale.html#locale.format
> Deprecated since version 3.7: Use [format_string()](https://docs.python.org/3/library/locale.html#locale.format_string) instead.
Closes #1061
> l10n: Use locale.format_string() instead of deprecated locale.format()

- .github/workflows/pr-checks.yml
- .github/workflows/push-checks.yml
- journal_lock.py
- tests/journal_lock.py/test_journal_lock.py
I happened to run `pytest` and found the journal_lock tests utterly broken.
In essence they changed the name of the "temporary directory factory", and by the looks of it also what references to it return. So, this adds some `.getbasetemp()` calls, and some wrapper `str(...)` where necessary to actually be comparing the correct things.
Also, a prior test could have left a lock file in existence when subsequent tests needed it to not be there in order to work properly, i.e. the "read only directory" test.  So I've added `release_lock()` and `os.unlink(...)` cleanups all over.
I've also now added an attempt to run `pytest` in the GitHub pr-checks, and bumped all reference to Ubuntu 18.04 to 22.04, as the former is deprecated.
> Fix up the journal_lock tests for pytest temporary directory factory changes

- tests/journal_lock.py/test_journal_lock.py
Mostly the test for 'already locked', which utilises a `multiprocessing` separate process to have the lock already held, was causing issues for later tests due to failure to properly remove the lockfile during its run.
I also checked that the tests *do* run properly on Linux, so have removed the comment about that test 'not working' on Linux, as we did implement the whole separate process thing.
It was also high time for removal of most of the top-level docstring text, which was initial thoughts on what tests would be needed.
I'm willing to be convinced that, actually, we should make each test use its own sub-directory so as to avoid any cross-test issues.  Those issues having been:
1. Another test left the lockfile in existence, which interfered with the "this user doesn't have …
> Finally(?) ensure all the tests work, no contamination or races

- .coveragerc
- Contributing.md
- config/__init__.py
- config/darwin.py
- journal_lock.py
- pyproject.toml
- requirements-dev.txt
Due to that EDDN branch causing me to keep thinking "I should add tests" I decided to look at our coverage.
That lead to fixing things to produce a coverage report that is actually correct on simply running `pytest`, but only if no test fails.
Then it became clear that our `sys.platform` branched code was a problem, and I found the `coverage-conditional-plugin` module to help with that.
It does help in the branch cases, and for other single lines, but currently is of no use for whole files.
This PR should attempt to `#pragma` up as much as possible before merging.
I'm torn on the semantics of the names of the rules versus their usage.  Citing a pragma means that if the test in its definition returns `True` that code section is *ignored* for coverage reporting.  Currently there's …
> Improve pytest coverage setup and usage

- plugins/eddn.py
Currently `https://github.com/EDSM-NET/EDDN/wiki` is being forwarded to `https://github.com/EDCD/EDDN/wiki` already and that page says one should read the readme instead of the wiki, so we should adjust the URL in EDMC. I'm open for the exact URL though (link to README.md directly, use anchor or not..).
> Fix URL for EDDN GitHub Link

- EDMarketConnector.py
- PLUGINS.md
- config/__init__.py
- monitor.py
- plugins/eddn.py
- prefs.py
1. The current `replay.json` has to be entirely rewritten if any message is added or removed.  That's just crap.  Either it churns to disk or risks losing data until a `flush()`.
2. The current code explicitly never queues station data messages.  The premise was "this is ephemeral data and another Cmdr will be along soon enough", but that's misguided.
3. 'Replay' was only ever triggered by being docked.  This is fine for a strict replay scenario, but not where initial sending of a message failed and it should be retried.  Cmdrs out in the black, without 'delay sending until docked' would have long delays in anything else being sent.
So, a partial rewrite.  At this time most of the functionality is working:
1. There's a new class `EDDNSender` to hold the queue and actual transmission code. …
> Change EDDN 'replay' to using an sqlite3 DB & otherwise improve

- EDMarketConnector.py
- L10n/en.template
- PLUGINS.md
- companion.py
- plugins/eddn.py
- #1733 - Disable CAPI functionality for Legacy players.  There's logging *and* a new status UI string, but the latter isn't intended for translation as this should be a short-lived measure.
- #1734 - Set improved `game_version` for CAPI-sourced data on EDDN messages.
> Improve CAPI code for Legacy/Live split

- .github/workflows/pr-checks.yml
- .github/workflows/push-checks.yml
- EDMarketConnector.py
- config/linux.py
- journal_lock.py
- loadout.py
- myNotebook.py
- plug.py
- plugins/eddb.py
- plugins/edsm.py
- plugins/edsy.py
- protocol.py
- scripts/killswitch_test.py
- shipyard.py
- td.py
- theme.py
- ttkHyperlinkLabel.py
- update.py
- util_ships.py
Because of the change in flake8 6.0.0 (`--diff` no longer exists, and it turns out it was always unreliable, hence it being removed), we need to move to just running it on whole files.
But some of the details about how to achieve that are ... awkward.   So, as per #1723 we need to get all of our code passing flake8 tests such that we can *then* adjust the github workflows, and pre-commit config, to always run on whole files.
**THEN** we can actuall upgrade to flake8 6.0.0+.
Now complete
---
I did endeavour to check code was still working as I went, file by file, so this *should* be good to merge.
> Get everything passing flake8 checks

- plugins/eddn.py
If no 'live' Journal events yet, plugins/eddn won't have had an event to set this from.
> eddn: Ensure CAPI-sourced messages have uploaderID set

- PLUGINS.md
- monitor.py
This is to allow restart of EDMarketConnector whilst the game is running to have `state['NavRoute']` hold data when the synthetic `StartUp` event is passed to plugins.
Closes #1739
> monitor/NavRoute: Load NavRoute after catching_up ends.

- .mypy.ini
- EDMarketConnector.py
- PLUGINS.md
- companion.py
- plug.py
- plugins/eddn.py
- td.py
There's a separate CAPI host for Legacy data.  Enable use of this.
Closes #1728
> CAPI: Enable use of Legacy host when applicable.

- EDMC.py
- monitor.py
- plugins/eddn.py
* Changes the `GameVersion` we found logging from INFO to DEBUG.  Thus not polluting normal EDMC.py output.
* Fixes `EDMC.py -n` to work again - mostly avoiding trying to set tkinter Label text when there's no GUI.
> EDMC.py quietening and fixes

- Build-exe-and-msi.py
- EDMarketConnector.py
- config/linux.py
- hotkey/darwin.py
- hotkey/linux.py
- hotkey/windows.py
- myNotebook.py
- protocol.py
- tests/config/_old_config.py
Some simple-ish changes to make mypy stop being upset that linux exists.
Tested that EDMC does still launch (on linux)
- config/linux.py Fix mypy complaints
- tests/config: Disable mypy on _old_config.py
- build: add "dumb" platform check for mypy
- myNotebook.py: Make platform check simpler
- hotkey/linux.py: Update stub
- hotkeys/windows.py: Add explicit platform check
- EDMarketConnector.py: Guard platform specific func
- protocol.py: Make mypy happy
> Make mypy happy on linux

- .github/workflows/windows-build.yml
- .pre-commit-config.yaml
- Build-exe-and-msi.py
- prefs.py
- protocol.py
- stats.py
Given the `py2exe` deprecation of 32-bit packages I decided it was time to take another stab at getting our .exe files to run under 64-bit Python.
After some fiddling around with ctypes, and re-testing showing we **can** just use `tkinter.filedialog` now (last tested under Python 3.7.x in Oct 2020), the code now all works under 64-bit Python 3.10.8 (and also 3.11.0).
* `Build-exe-and-msi.py` has been adjusted to check for, and require, 64-bit, not 32-bit, Python.
* You need the `x64` version of the `WinSparkle.dll` (~~still need to adjust the github workflow for that~~ done).
* All the files that had `ctypes` in them have had all their code tested as working on 64-bit.
* For that "Where should the Output file location be?" code in `prefs.py`... I really did try to get the old ctypes code …
> Make runnable under 64-bit Python

- EDMarketConnector.py
- PLUGINS.md
- plugins/eddb.py
- plugins/eddn.py
- plugins/edsm.py
- plugins/inara.py
Given talk about adding the ability to change the UI ordering of third-party plugins I started looking at the totality of plugins in the main UI.  Most of them had no `name=...` in their creation so ended up with non-useful tkinter names.  This PR ensures each one has a pertinent name.
Then I experimented with creating a per-plugin frame for all its UI to be in, rather than it being directly in the main UI Frame.  This appears to have no ill effects on the three plugins with UI I have running (aussi's BGS-Tally, Hourly Income and FCMS).  The one piece of fallout was to switch to `nametowidget()` in some of the core plugin code where it needs to access system/station widgets or set status text.
There is no sanctioned reason for a third-party plugin to be trying to poke at/get information …
> UI: Properly name main widgets & put each plugin in its own Frame

- .github/workflows/windows-build.yml
Because the GitHub automatic .zip (and .tar.gz) archive is based purely on the files in *this* repo it doesn't include the two necessary files from the FDevIDs sub-module.
So, this PR adds an extra build step to make such an archive *with* those files.  Actually I felt it easiest to just include all the FDevIDs files.  The resulting .zip file is then an extra build artifact which is included in subsequent steps, i.e. hashes.sum and release draft creation.
I've left the most recent successful draft release at https://github.com/EDCD/EDMarketConnector/releases/tag/untagged-d68b90c527b0e582d027 (likely only viewable by collaborators).
We should be able to extend this to a custom .tar.gz as well.
Close #1801
> Create a custom .zip archive for releases

- EDMC.py
- EDMarketConnector.py
- PLUGINS.md
- monitor.py
- plugins/eddb.py
- plugins/eddn.py
- plugins/edsm.py
- plugins/inara.py
As well as being duplicate code in the core plugins, there's also a bug related to plugins not receiving events during Journal catch up.  This means that current release plugins/eddn.py code doesn't properly know where it is if you relog on a body surface, meaning the CodexEntry handling then doesn't have the data for cross-checks.
Fix this by extending monitor.state tracking to include the necessary data, and relying on that in the EDDN plugin.
NB: Still need to check the *other* core plugins to update their tracking to reflect they can just rely on `journal_entry()`'s `state` now.
Closes #1042
> Move core plugin 'location' tracking into monitor.py

- .github/workflows/submodule-update.yml
No-one seems to have cared to apply any of the auto-generated PRs, or to make this small change.
Apply this, apply the latest 'spam' PR, then delete all the other 'spam' PRs.
> Switch off the submodule PR cronjob in favour of 'push to develop'

- .github/workflows/submodule-update.yml
- ChangeLog.md
- EDMarketConnector.py
- build.py
- config/__init__.py
- plug.py
- plugins/edsm.py
- plugins/inara.py
- resources/EDMC_Installer_Config_template.txt
Fixes a critical bug with the installer on new installs not creating registry keys (#2046)
Also includes a number of minor enhancements:
- Re-enables automatic submodule updates (#1443)
- Allows Help -> About Version String can now be copied to clipboard (#1936)
- EDSM Task Manager Printout now is less useless (#2045)
- Deprecated load_module() is now retired (#1462)
- API Keys are masked in Settings (#2047)
- Installer will now refuse to install on Win7 and Earlier (#1122)
> 5.9.2 Collective Roundup - Frontier Auth Registry Keys

- companion.py
- config/__init__.py
- resources/EDMC_Installer_Config_template.txt
This Pull fixes an additional issue with the new installer and the EDMC:// protocol. This puts in a more preferred handler key to ensure traffic is redirected appropriately. This is a temporary fix, and the next version (5.10.0) should investigate inverting the preference of the EDMC protocol vs local authentication. 
Also changes the name of the default shortcut to be clearer.
Fixes #2057, #2058, #2059, #2062
- Adds additional handler key to Windows registry
- Adds a message box that displays on a successful authentication event.
- Bug Fix 
- Multiple install runs, clean installs, self-updates, and others made to …
> Fix cAPI Hanging Auth Issue on EDMC Protocol

- EDMarketConnector.py
- prefs.py
This Pull adds a menu option to open the file that logs are stored in the help menu and adds the same option to the preferences menu. This will allow for easier locating of logs and also resolves a long-standing request. 
Fixes #510
- Adds Open Log Folder to Help Menu
- Adds Open Log Folder to Config Menu
- New feature (non-breaking change which adds functionality)
- Tests with included alterations to Release auto build made and output confirmed.
- Multiple install runs, clean installs, self-updates, and others made to confirm functionality
> #510 Open Log Directory

- .github/workflows/windows-build.yml
Updates the build Github action to automatically poll the GitHub API and pull the latest version of WinSparkle. This will ensure that we are using the latest version should a new version be released without needing to set it in the action manually. Yay, automation!
Closes #1009 
- Updates GitHub action to use the latest API release. 
- Feature Enhancement - improves existing features in a non-breaking manner
- A test build was successfully completed using GitHub actions on a private repository. The test artifact worked successfully and the action was completed without error.
> Force Latest Winsparkle for Builds

- plugins/inara.py
Looks like Inara changed their URL format. When visiting it for the first time, I had to choose for which game I'm coming. After choosing Elite, the old links work again. But these seem to be the correct ones.
> Fix Inara URLs for station & system search

- plugins/coriolis.py
- plugins/eddn.py
- plugins/edsm.py
- plugins/edsy.py
- plugins/inara.py
Broken out of #2068
This is a full-pass update to the core plugin files, containing a major SemVer-compliant logic overhaul to the files. These updates are intended to optimize existing code, update older Python 2 style code to more updated standards, and increase readability and compatibility. 
- Multiple install runs, clean installs, self-updates, and others made to confirm functionality, including under a variety of existing pre-install situations. 
- Tested by the EDMC Internal Alpha Group and initial bugs fixed.
> [2051] Core Plugin Audit

- .gitignore
- config/__init__.py
- config/darwin.py
- config/linux.py
- config/windows.py
- plugins/coriolis.py
- plugins/eddn.py
- plugins/edsm.py
- plugins/edsy.py
- plugins/inara.py
- tests/EDMCLogging.py/test_logging_classvar.py
- tests/config/_old_config.py
- tests/config/test_config.py
- tests/journal_lock.py/test_journal_lock.py
- tests/killswitch.py/test_apply.py
- tests/killswitch.py/test_killswitch.py
Broken out of #2068
This is a full-pass update to the core config files, containing a major SemVer-compliant logic overhaul to the files. These updates are intended to optimize existing code, update older Python 2 style code to more updated standards, and increase readability and compatibility. 
- Multiple install runs, clean installs, self-updates, and others made to confirm functionality, including under a variety of existing pre-install situations. 
- Tested by the EDMC Internal Alpha Group and initial bugs fixed.
> [2051] Config Files Audit

- .github/workflows/windows-build.yml
- docs/examples/click_counter/load.py
- docs/examples/plugintest/load.py
- plugins/edsm.py
- requirements-dev.txt
- scripts/find_localised_strings.py
- scripts/killswitch_test.py
- scripts/pip_rev_deps.py
- util/text.py
- util_ships.py
Broken out of #2068
This is a full-pass update to some of the supporting files for EDMC. Primarily, these contain logic overhauls to the files. These updates are intended to optimize existing code, update older Python 2 style code to more updated standards, and increase readability and compatibility. 
This also includes development requirements updates and a simplification of the winsparkle pull process.
- Multiple install runs, clean installs, self-updates, and others made to confirm functionality, including under a variety of existing pre-install situations. 
> [2051] Utilities, Scripts, Workflow Audits

- plugins/coriolis.py
- plugins/eddn.py
- plugins/edsm.py
- plugins/inara.py
- prefs.py
The UI in the settings panels is currently not standardized. The Paddings used vary wildly with signs of a pattern that's not used everywhere though. This creates a standard for the settings UI and applies it to the panels. This standard can also be used as a reference for future updates and be given to Plugin developers to achieve a uniform look.
Closes #2088, #2089, #2095
- Fixes indentation on non-English languages with varying character spacing
- Fixes a number of issues with labels overwriting the content they are displaying on
- Implementation of settings UI standard
- Multiple install runs, clean installs, and …
> Fix and standardize Settings UI

- collate.py
- debug_webserver.py
- journal_lock.py
- myNotebook.py
- theme.py
- timeout_session.py
- update.py
Updates 7 of the supporting core EDMC files with a Semver-compliant pass. Updates type hints to modern-style standards (PEP 585), removes a few Python 2-era definitions, and clarifies some unions and attribute checkers.
Derived from #2068 
- Tests of installation, operation, and building on developer machine
> [2051] Update Supporting Files

- build.py
- coriolis-update-files.py
- docs/Releasing.md
- edshipyard.py
- outfitting.py
- resources/modules.json
- resources/ships.json
Updates a few more of the supporting core EDMC files. The biggest change here is removing the usage of ships.p and modules.p, and replacing them with json equivalent files. This is a security and readability update, as Pickle has a number of serious concerns about it's existence. 
Due to API requirements, we can't just remove it here. However, these files are officially deprecated and should be removed in 6.0.
Additionally, makes a few enhancements and logic flow improvements to existing code.
Derived from #2068 
- Deprecation of Old Methods
- Tests of installation, operation, and building on …
> [2051] Convert Pickle to Json

- build.py
- plugins/edsm.py
- plugins/spansh_core.py
This adds spansh as a URL provider for system and station URLs. It does so by adding a core plugin called ``spansh_core`` with said functionalities. The reason for that name is to make sure that custom plugins called ``spansh`` that users may already have installed don't result in either of these two plugins breaking. The ``spansh_core`` plugins is also designed to be expandable in the future if additional features should be added.
Closes #1490 
- Adds a spansh plugin as a URL provider for systems and stations.
- Multiple install runs.
- Tested Plugin and core functionality in all relevant in-game situations.
- All …
> Add spansh as a URL provider

- EDMC.py
- EDMCLogging.py
- EDMarketConnector.py
- dashboard.py
- killswitch.py
- l10n.py
- loadout.py
- protocol.py
- ttkHyperlinkLabel.py
Updates a few more of the supporting core EDMC files. The focus here is to retire outdated typing hints, improve overall readability, and implement minor pythonic improvements. 
Additionally, where practical, if both os.path and pathlib are in use, one has been chosen instead of mixing both. 
A new command flag for EDMC has been added, the `--start_min` flag. This attempts to instruct the program to start minimized.
Derived from #2068.
Closes #1379.
- Addition of new features
- Tests of installation, operation, and building on the developer's machine
> [2051] Additional Core Files

- build.py
- companion.py
- docs/examples/click_counter/load.py
- hotkey/__init__.py
- hotkey/darwin.py
- hotkey/linux.py
- hotkey/windows.py
- monitor.py
- outfitting.py
- plug.py
- plugins/eddn.py
- prefs.py
- stats.py
The last of the supporting files for EDMC. This will (to my knowledge) complete a first-pass run on all the EDMC files.
The focus here is to retire outdated typing hints, improve overall readability, and implement minor pythonic improvements. 
Derived from #2068.
- Addition of new features
- Tests of installation, operation, and building on the developer's machine
> [2051] First Pass Remaining Files

- companion.py
In rare edge cases, how the API authentication key is called can be sent to the web browser incorrectly, meaning that the request fails on the API scope query. This endeavors to remove the ambiguous space, given the evidence and logs provided in #1843. 
- Minor Bug Fix
- Tests of installation, operation, and building on the developer's machine
Closes #1843
> [1843] Update URL Parameter Encoding

- build.py
- config/__init__.py
- config/windows.py
- docs/Translations.md
- resources/EDMC_Installer_Config_template.txt
Attempts to move the WinSparkle key creation from the Windows config itself to the InnoSetup INI file. This is done in such a way as to try and reduce some overhead as well as create these values if and only if they don't already exist. 
- Feature Enhancement
- Tests of installation, operation, and building on the developer's machine
- Manual edits of registry values to test survivability
Closes #555
> [555] Move Default Registry Creation

- EDMarketConnector.py
- L10n/en.template
- coriolis-update-files.py
- plug.py
- prefs.py
Adds a popup at startup about plugins that failed to load, presumably due to a wrong folder structure. This popup will come up at every EDMC start, unlike the "Plugin without Python 3.x support" one that only pops up every 24h. This PR also adds a list of those Plugins under their own entry in the Settings - Plugins tab.
- Adds a Popup at startup about Plugins that failed to load.
- Adds entry about broken Plugins in the Settings - Plugins tab.
- Adds corresponding translation entries.
- Includes a minor fix for try/except if coriolis-data is missing.
- All PyTest tests pass.
- `find_localised_strings.py` doesn't …
> Broken Plugins Popup

- EDMarketConnector.py
- L10n/en.template
- build.py
- companion.py
Adds a popup at startup about missing FDevIDs files on startup to EDMC. This popup will come up at every EDMC start, unlike the "Plugin without Python 3.x support" one that only pops up every 24 hours. This includes an option to open the wiki to view the instructions for installing the Git Submodule. 
This should only be an issue encountered if running from the source, as the packaged/distributed installs will include this information and files by default. The popup is designed so that it will only pop up once even if both fdevid files are missing or only one is missing. 
- Adds a Popup at startup about Plugins that failed to load.
- Adds corresponding translation entries.
- All PyTest tests pass.
- `find_localised_strings.py` doesn't complain.
- Tested feature with missing and found …
> [1801] Add Warning for FDevIDs

- config/__init__.py
In #2084, we updated a general "except Exception" to a more specific subprocess.CalledProcessError. In doing this, we failed to account for an edge case that could occur if you were running from source but did not have Git installed. This fixes that edge case.
- Bug fix
Closes #2125
> [2125] Updates Exception Check

- EDMarketConnector.py
Fixes a bug introduced in 724dd2ce6af07c8be10a4a7eabb72b91d2d2fe2d
These imports are indeed duplicates, however, they are required for the "an instance of EDMC is already running" popup to function as intended.
> [Fix] Add Required Dupe Imports

- EDMarketConnector.py
- hotkey/darwin.py
- hotkey/windows.py
- outfitting.py
- plug.py
- plugins/inara.py
- tests/config/_old_config.py
- ttkHyperlinkLabel.py
Tuples are (slightly) more efficient for comparing if x in y. While this resource savings is not particularly notable at our scale, it is still a good Pythonic standard to implement here. This PR attempts to implement the change in all core files except theme.py.
- Minor Edits
Closes #2122
> [#2122] Handover a number of Lists to Tuples

- companion.py
- coriolis-update-files.py
- edmc_data.py
- l10n.py
- monitor.py
- outfitting.py
- plugins/eddn.py
- plugins/inara.py
Before Python 3.7, Dictionaries did not maintain their order by default. However, in the modern age of Python, Dictionaries do maintain their order and this import and complication is largely unnecessary. This removes all orderedicts from the project. 
This is technically a 3.11 milestone task, however can be done as a drop-in replacement patch in the 5.10.x line.
- Old Code Rewrite
Closes #635
> [635] Remove Ordered Dict

- EDMarketConnector.py
EDMC does not clean itself up cleanly after a ctrl+c when running from the console. This enhancement attempts to force EDMC to clean itself up on a keyboard interrupt. 
- Minor Bug Fix/Feature Enhancement
Resolves #2146
> [#2146] Cleanup On KeyboardInterrupt

- EDMarketConnector.py
- L10n/en.template
In rare instances, if an invalid System, Station, or Plugin provider is set in the configuration (such as EDDB in Station or System provider), this can result in the program breaking. This alleviates this issue by checking if the set configuration values are valid at startup. If not, reset them to the default values and throw an error to the user. 
This fix also includes the required LANG changes to allow localization. 
- Bug Fix
Closes #2077
> [#2077] Ensure Providers Are Valid

- L10n/en.template
- plugins/coriolis.py
Currently changing languages may cause Coriolis URL overrides to revert back to auto (default) if the current selection has a different display string between the old and new language. This PR fixes that by saving the old display strings when creating the prefs window and checking against those when closing it. 
- Bug Fix
- Switching between languages with and without changing the override setting at the same time.
- Manually editing Registry to ensure original fallback to default still works.
Closes #1181
> [1181] Save Coriolis URL override when changing languages

- plugins/inara.py
In May 2023 a new parameter called ``isThargoid`` was added to the ``Interdicted`` and ``EscapeInterdiction`` journal events which caused issues with the way the Inara plugin handled Interdiction events. Additionally Thargoid caused deaths didn't show up in Inara's Combat Log.
This PR:
- Updates the Inara plugin to check for that ``isThargoid`` flag and set the ``opponentName`` in Thargoid related Inara API updates to ``Thargoid`` if it is set.
- Adds a check to the ``Died`` event to use the Killer's ship's name as ``opponentName`` if the Killer's name is not present in the journal entry (as is the case for Thargoid caused deaths).
- Rewrites the ``EscapeInterdiction`` path to match the other Interdiction paths.
- Updates the Interdiction related Paranoia checks to also work in cases of …
> [2163] Update Inara plugin to better handle Thargoid Combat events

- plugins/eddn.py
This fixes a bug introduced in #2139 which would result in EDDN messages not being properly sent. This ensures EDMC does not attempt to hash an unhashable list object.
- Bug Fix
Testing using provided recreation steps and ensuring EDDN messages are being sent successfully, which was not happening with the bugged version on startup.
> [#635] Properly Convert Message Object from OrderedDict

- EDMarketConnector.py
- L10n/en.template
From #901, If you didn't actually login during the last start of your game client then the latest Journal file doesn't have Commander information.
This adds a new "status" message to indicate the stage the player is on, to fill out some of the UI, and to indicate the application is not frozen or broken.
- Feature Enhancement
Testing using provided recreation steps. Tested to ensure that this status doesn't stick around when the login flow continues or this edge case isn't present.
Closes #901
> [#901] Add Additional Status for Incomplete Logins

- outfitting.py
Fixes a bug introduced in e268c24 where the handover from the Pickle system to the JSON system would result in broken outputs from one CSV file. 
- Bug Fix
Testing using provided recreation steps from TCE and coordination with TCE
Closes #2179
> [2176] Fix Outfitting Split

- plugins/eddn.py
Currently, the EDDN plugin sends all but two schemas to EDDN. The missing schemas are super simple to implement (DockingDenied and DockingGranted), and inform EDDN as to the reason for various docking events. This also helps us determine what the docking permissions on Fleet Carriers are!
This PR adds those two missing schemas. 
- Enhancement
- Output of the function tested in a sandbox before enabling
- EDDN docs verified correct
- EDDN schema returns validated response on testing
Resolves #2155
> [2155] Add DockingDenied and DockingGranted Schemas

- L10n/en.template
- build.py
- config/linux.py
- monitor.py
- myNotebook.py
- requirements-dev.txt
- requirements.txt
Adds a context menu including Cut, Copy, and Paste options to all nb.Entry fields, primarily those in the config menu. 
This has been tested to ensure that any secrets cannot be extracted by using this system. This also leverages existing nb systems, so legacy MacOS functionality will be maintained (though they will not get this new feature).
Additionally, contains a fix to a ctypes prototype function that could break on some source installs running using 64-bit Python (not currently officially supported) and updates some developmental dependencies. 
Includes a fix for a rare bug when running from source under #1805 
Finally, this PR also adds the Python Image Library (Pillow) (#1471, https://github.com/NoFoolLikeOne/EDMC-Screenshot/issues/51)
- Enhancement
- New Package
- Tested on …
> [1133] Add ContextMenu Globally

- edmc_data.py
- outfitting.py
TCE has identified an error where the new SCO modules weren't being detected by EDMC. This is a two-part issue: 
1) The FDEVID files which we use for a lot of things haven't been updated (https://github.com/EDCD/FDevIDs/pull/88)
2) We didn't have the code to process these oddly named modules. These two together caused a number of errors and caused EDMC to be considered "crashed" to some tools like TCE. 
While investigating this, it was discovered that if one of these missing modules (universal limpet controllers and some of the thargoid war stuff) was encountered, it would stop the module review and leave out-of-date or incomplete module exports from stations. 
This PR adds the logic to process these missing modules.
Resolves #2202
> [2202] Add a number of missing modules

- killswitch.py
- myNotebook.py
In the event of a connection issue to github, there are a number of errors and exceptions that can be thrown. A number of exception types are accounted for. Some are not. 
This PR changes to the general requests exception to handle, and prevent EDSM from crashing if the killswtich file cannot be contacted for whatever reason. 
Also includes a minor fix to the EntryMenu class which will allow greater plugin compatibility with existing plugins which use an unclear nb.Entry. 
Discovered by #2199
> [2199] Better Exceptions on URL Errors

- docs/examples/click_counter/load.py
- myNotebook.py
- plugins/coriolis.py
- plugins/edsm.py
- plugins/inara.py
- prefs.py
- requirements.txt
The previous PR to remove macOS support (#2187) was a little too overzealous and removed the functionality added by #2183 by converting the usage of nb.Entry to ttk.Entry instead of the intended nb.EntryMenu. 
nb.Entry usage still should be eliminated, but the alternative should be our menu class. 
Also clarifies some side issues and details. Removes a [GNDN](https://www.urbandictionary.com/define.php?term=GNDN) line of code which we don't need. 
Resolves #2186 
All other details of #2187 are still valid.
> [2186] Refine macOS to preserve ContextMenu

- util_ships.py
This PR adds additional robust checking to make sure that a ship name is not in the Windows Reserved Filename list. This removes the older self-maintained version, and dumps the responsibility for that on Python's Pathlib module. (Why replicate existing work?)
This slightly renames how ship names can be output, however, remains safe for use in Windows and Linux (Linux will accept any filename). 
- Feature Enhancement
Tested on a number of ship names using Windows reserved naming schemes. (Hello con, the Adder!)
Resolves #1268
> [1268] Handover to Path.is_reserved()

- edmc_data.py
- edshipyard.py
- outfitting.py
- ships.json
This PR addresses the first of probably many issues that will be presented by Elite: Dangerous update 18.04. This issue is due to the fact that the exact details of the new frameshift drive modules are not in any of the sources that EDMC uses, and is required to calculate a user's jump range when using the new SCO modules. 
The eventual fix for this will need to come in multiple stages. First, the exact module details for each of the SCO modules (including any changes to the fuelmul and fuelpower constants) will need to be extracted. For EDMC, we use Coriolis's data library for this information. 
Once those numbers are known, they'll need to be added to Coriolis (this is simple to do, just time-consuming for the nearly 40 modules). That will come in a later PR. 
Without these updated …
> [2228] Handle Unknown FSD Ranges

- EDMC.py
- EDMarketConnector.py
- PLUGINS.md
- companion.py
- docs/Translations.md
- journal_lock.py
- l10n.py
- monitor.py
- myNotebook.py
- plugins/coriolis.py
- plugins/eddn.py
- plugins/edsm.py
- plugins/inara.py
- prefs.py
- scripts/find_localised_strings.py
- stats.py
- theme.py
- ttkHyperlinkLabel.py
- update.py
Currently, the translation system works by forcing itself into Python's builtins. This is against current good practice, and can cause issues with identifying where functions come from, can cause issues with interoperability with plugins, and can introduce a number of issues in development with IDEs and debugging alongside pollution of the namespace. 
This implements a conversion of the translation function away from using the builtins modules and into using the explicit singleton "translations" (shorthand: tr) for the translations (tr.tl). This also adopts modern Pythonic standards of renaming the `_Translations()` function to `Translations()`, and renaming the default singleton of `Translations` to `translations`.  
The current singleton (`Translations`) is maintained, but marked as …
> [1812] Rename the Translation Function

- config/__init__.py
- requirements.txt
Certifi and charset-normalizer are dependencies of Requests. As such, we should let Requests handle which version those programs want without pinning them ourselves. This reduces the overhead we have to maintain as well as helps to prevent issues with dependency updates. 
Additionally, removes argh and pyyaml for similar reasons. 
- Dependency Update
- Building with clean environments and on GH actions to ensure that the required dependencies are included.
Resolves #2198
> [2198] Cleanup Dependency Clutter

- plugins/inara.py
As of mid-2022, Inara includes the ability to set the maximum ship jump range and cargo capacity of a given ship to the setCommanderShip event. This PR adds that data to the information we send to Inara, and increases the number of places where this data event is updated. 
This is done by processing this data anytime a Loadout event is sent, including on session startup as all of the data needed can be found on startup events. Additionally, the update for setCommanderShip is moved out of shipswap events and into any time the Loadout event is recorded by the game. 
* Enhancement
* Tested with various setCommanderShip event triggers to determine where data is available 
* Ensured duplicate events are not sent to Inara where possible on Loadout events
Resolves #1654
> [1654] Add Ship Jump Range and Cargo Capacity to Inara

- EDMarketConnector.py
- prefs.py
Currently, when choosing "Open Plugin Location" on Linux, the system calls the web-browser and instead opens the directory in the web-browser instead of the file explorer. This is sub-optimal. Instead of calling the web-browser, this PR instructs the OS to open the file or folder indicated natively. 
This is done by leveraging the `help_open_log_folder()` function (renamed to `open_folder()`), and generalizing the file. The existing `help_open_log_folder()` is deprecated and slated for removal in 6.0. 
- Enhancement
- Tested in available Windows and Linux builds to ensure that the file does not open in a webbrowser.
Resolves #830
> [830] Open Log Folder Natively

- monitor.py
- requirements.txt
Watchdog 4.0.0 included an update to the public API where FileSystemEvent, and subclasses, are now dataclasses, and their repr() has changed.
As such, (insofar as I can tell) the FileCreatedEvent is now a FileSystemEvent. MyPy also suggests that this is a FileSystemEvent as well. This type hint change should have no practical impact on the code, only how items that are calling this function expect data from it. 
* Minor Fix
* MyPy tests, boot tests, and minor gameplay time to ensure no new errors are generated.
Replacement for #2166
> [2166] Update Watchdog Type Hints

- EDMarketConnector.py
- L10n/en.template
This PR adds a high-level error handler for critical errors that are not properly handled inside of EDMC. This handles elements that can lead to the program crashing on startup and includes errors where the program may look like it's not working at all. 
This improves the user's experience and also encourages users to report errors to us on GitHub so that we can discover and fix errors more often - or at least direct the user on how to fix the error. Also includes the relevant translation information. 
Additionally, simplifies the "An EDMarketConnector process was already running" popup to utilize tkinter.messagebox elements, which significantly reduces the amount of overhead needed to show the prompt and also makes the prompt more clear that it is an error. 
- New Feature
Tested with …
> [2203] Implement Total Exception Handling

- EDMarketConnector.py
- L10n/en.template
- myNotebook.py
- ttkHyperlinkLabel.py
This feature adds a pop-up menu for the three core HyperlinkLabel elements on the main UI (that is, Ship, System, and Station). This menu includes the ability to open the selected element in any of the available URL providers, even the ones that are not currently selected in the configuration system. This also enables the "Copy" option on the Station and Ship elements. This also adds a new translation check for the needed elements. 
- New Feature
Relies upon #2209 for the updated translation system. Until that PR is merged in, this will appear with a larger diff than it really has. 
Resolves #1173
> [1173] Add Right-Click Menu to UI Elements

- plugins/edsm.py
Fixes an issue that could present on clean installs where the EDSM keys weren't generated properly. This will set the key if totally missing, else try and extend a mismatched API set with null values when able. This issue would most often present itself on clean installs.
Bug Fix
Tested with mismatched, missing, and malformed EDSM preferences key entries, and ensuring the program recovers successfully from the reported replication steps. 
Resolves #2232
> [2232] Fix Missing Preferences

- L10n/en.template
- myNotebook.py
- ttkHyperlinkLabel.py
This PR fixes a few identified bugs with newly added features to EDMC, particularly the right-click pop-up menus on the main window for opening items in alternate providers. 
1. Adds three new translatable strings
2. Fixes a bug that could result in alternate URL providers not opening the proper resource
3. Fixes a bug that could result in changing languages not properly translating the right-click pop-up menus until a full restart
- Bug Fix
Tested with multiple languages and URL provider conditions
> [Fix] Update Translations, Fix Menu Creation, Fix Alt URL

- EDMarketConnector.py
- build.py
- collate.py
- companion.py
- config/__init__.py
- update.py
This PR fixes an issue that could occur when non-installer distributions running in locations where the running users can't write to couldn't pull and update their FDEVID files. This alters the system to write to the same general location as the Plugins folder is located, as well as run the fdevid updater on startup. 
This also adapts the function to accept a "local" argument to try and force the program to update the files at the same location as the program itself, such as for builds or for backward compatibility (although backward compatibility with the FDEVID files has never been guaranteed).
Also adds a sanity check to the addcommodity function just as a quick safety net. 
Fix
Tested with the EDCD Discord including several Linux developers who pointed out this issue.
Closes #2251.
> [2251] Fix FDevID Update Paths

- EDMCLogging.py
- EDMarketConnector.py
- config/__init__.py
- l10n.py
- myNotebook.py
- prefs.py
- requirements-dev.txt
- requirements.txt
Our use of `DeprecationWarning` falls into two traps described in [the `warnings` library documentation](https://docs.python.org/3/library/warnings.html):
1. Since Python 3.7 this particular warning is not shown by default, unless triggered directly in `__main__` (or the `-W` argument is set on the interpreter)
2. Calls to `warnings.warn()` display their own lines, which defeats the purpose of `DeprecationWarning` - the `stacklevel` exists for that, pointing one level down to the plugin function calling them.
A convenience for plugin developers which would otherwise miss that they are using deprecated functions.
Running the latest version of some plugins showed immediate results - the use of `myNotebook.Label` being particularly common.
> Enabled DeprecationWarning by default and fixed references

- EDMarketConnector.py
In 5.11.1, a handover occurred from the older/out of date infi.systray to a more updated fork, simplesystray. This worked for the most part, however, a few edge cases showed this fork was not as drop-in a replacement as we were lead to believe.
This fixes the issue (reported in #2256) by allowing the open_window() function to accept any number of variables, with a minimum of 1. This works with both infi.systray and simplesystray logic.
Bugfix
Tested with various iterations of minimize to tray and on both infi and simple systray.
Closes #2256.
> [2256] Allow Variable Num of Variables

- .gitignore
- requirements-dev.txt
- scripts/build_changelog.py
This PR adds a utility which can automatically extract, from ChangeLog.md, the latest version's changelog and build the Reddit, FDev Forum, and HTML (for appcast) versions of the changelog. This utility will help speed up the release pathway for announcement generation. This is a standalone utility and does not interact with any core EDMC code. 
New Utility
Tested multiple iterations of the latest release's changelog through the system.
Closes #525
> [525] Add ChangeLog Tooling Utility

- debug_webserver.py
This PR updates the method in which debug_webserver.py's SAFE_TRANSLATE string is formatted. This is done in accordance with [flake8-comprehensions](https://github.com/adamchainz/flake8-comprehensions) C420 definition declared in version 3.15.0
Enhancement
Linter-Generated Update, equivalent code output. 
Cause of failed tests in #2270
> [2270] C420 Unnecessary Dict Comprehension

- EDMarketConnector.py
- L10n/en.template
- config/__init__.py
- config/linux.py
- config/windows.py
- prefs.py
This PR enables the ability for users to customize their plugin directory away from the default directory's "plugins" folder. This allows users to swap between multiple different plugin "profiles". This does require a restart, so also adds an ability for EDMC to forcefully shut down and restart itself. 
Additionally, this updates the post_args callback to not force the settings window to be half-rendered during the callback. This is done by performing two callback operations at various stages with different payloads. While this is slightly duplicative, the impact is negligible. The loading of the Windows config also happens sooner in the program start-up, simply to allow the config to load the new customizable location sooner. This key is created at runtime if it does not exist. …
> [748] Allow Custom Plugins Directory

- EDMCLogging.py
- EDMarketConnector.py
- debug_webserver.py
- prefs.py
This PR moves the default logging directory away from $TEMPDIR or %TEMP% and to the current app data directory (Linux: `~/.local/share/edmarketconnector/logs`, Windows: `%localappdata%/edmarketconnector/logs`). 
This change is done to better follow the XDG Base Directory specifications, and to unify where files exist to fewer locations. (From up to 3 locations down to 1 for log files, plugin data, and other app files). 
Enhancement
Tested with various builds and install locations with both installers and user-frozen exe's to ensure logging refers correctly without errors. 
Resolves #2215
> [2215] Move Logging Directory

- EDMC.py
- EDMCLogging.py
- EDMCSystemProfiler.py
- EDMarketConnector.py
- build.py
- collate.py
- commodity.py
- companion.py
- dashboard.py
- docs/examples/plugintest/load.py
- installer.py
- l10n.py
- loadout.py
- monitor.py
- plug.py
- prefs.py
- theme.py
- ttkHyperlinkLabel.py
This PR hands over the majority of os.path related functionality to the more modern pathlib environment. This change is designed to unify filesystem operations and not split EDMC across two different libraries. Every effort has been made to maintain compatibility, with the hopes that this is a seamless handover.
Enhancement
Tested to ensure as seamless a transition as possible is performed. Tested in builds and installer runs. 
Resolves #2114
> [2114] Pathlib Handover

- EDMarketConnector.py
- config/windows.py
- hotkey/windows.py
- l10n.py
- monitor.py
- prefs.py
- protocol.py
- requirements-dev.txt
- requirements.txt
- stats.py
- theme.py
This PR hands over duties for a number of direct calls to the Win32 API to the pywin32 library. These calls help properly prototype a number of used functions and reduce reliance on the direct calling of the Win32 API. 
This has the added benefit of helping to properly set up the code to be more stable and reliable when using built 64-bit versions of EDMC. Where pywin32 isn't available, proper prototyping of direct win32 api calls h ave been performed to enhance stability.
Additionally, makes changes to enable the usage of game_running() on Linux. 
Enhancement
Tested using multiple local builds of EDMC on 32 and 64 bit Windows and ensuring the program executes properly.
Related to #1805 (though a second look is due when pywin32 307 comes out)
Replaces #1808
Closes #610
> [1805] Prototype More Functions

- monitor.py
- requirements.txt
`psutils` 6.0 added a new change to process_iter which improves performance substantially to the point where it is now actually worth using. The function `no longer checks whether each yielded process PID has been reused` per PSUtils docs, which generates an ~20x speed-up to use, which actually makes it worth using versus iterating through functions. This shaves almost half a second off of my testing, meaning less app freezes and a better working check. 
Enhancement
Tested and timed on my system running from source
https://github.com/giampaolo/psutil/issues/2396
> [610] Improved process_iter

- plugins/eddn.py
The old workaround appears to be not needed anymore. EDDN accepts NavRoute with Horizons/Odyssey flags now.
EDDiscovery, EDO Materials Helper and others also set these flags.
Removed workaround code from when EDDN did not accept these flags in NavRoute events.
I built and installed a release, produced NavRoute events and watched them come through the EDDN gateway.
Mentioned in #1310
> pass Horizons/Odyssey flags in NavRoute

- .github/workflows/pr-checks.yml
- .github/workflows/push-checks.yml
- .github/workflows/submodule-update.yml
- .github/workflows/windows-build.yml
This is in reaction to what happened ref: <https://www.wiz.io/blog/ultralytics-ai-library-hacked-via-github-for-cryptomining>
I think I caught all the instances.  I'd double-check the `windows-build.yml` changes as the variable references are github-workflow style rather than shell.  If what I did doesn't work you might have to explicitly assign the values to shell variables then use those **with the `"..."` quoting**.
> Guard against workflow shell execution vulnerabilities

- PLUGINS.md
- monitor.py
Adds the following stats which are present in the 'Loadout' event to the 'state' for journal_update:
```
"UnladenMass": float,
"CargoCapacity": int,
"MaxJumpRange": float,
"FuelCapacity": {
"Main": float, //could probably be int?
"Reserve": float
}
```
Also updates the Plugins Readme to match the changes.
Enhancement to existing 'state' tracking feature.
First submission so no serious regression testing, thanks in advance for the review.
Tested that any permanent changes to these properties should be accompanied by another 'Loadout' event, meaning adding them should never result in odd desyncs with the actual game state, please correct me if I'm wrong.
Compiled EDMC with changes and verified `state` properly contains the new values when I dump state:
```
{
"ShipID": 17,
"ShipIdent": …
```
> Include 'missing?' Loadout event properties in 'state'

- PLUGINS.md
- monitor.py
- plugins/inara.py
Adds some code to `monitor.py` as well as the Inara plugin to track Powerplay 2.0 rank, merits, and more
New Feature
Ran EDMC with some debug code to make sure that `monitor.py` would pick up on the PP event. Inara also tested and confirmed working, I was able to refresh my profile and see the new up to date rank and merit count on starting the game.
Fixes #2371
> Add code to track PP2.0 rank, merits, etc

- plug.py
Fixes timechecker on develop.
EDMC as it is on the develop branch right now skips every event for me.
(unless of course I started it with --skip-timecheck)
Flipped the comparison operator in plug.py so that the error message gets shown and skip happens when:
dt (which is the datetime object from the timestamp in UTC+0).
is lower (or longer ago)
than 60 minutes lower (or before) the time right now in UTC+0.
Also made all the datetime objects timezone aware to be able to compare with `datetime.now(timezone.utc)` avoid using `utcnow()`
See big red warning in python docs to datetime.utcnow: https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow
Additionally utcnow() is deprecated from python 3.12 onwards.
Bug fix
Temporarily used logging to show me each of the datetime …
> Fix Timechecker on develop

- monitor.py
Fixes #2360
I'm not saying that this is exactly how the fix should look like but it displays the issue. Raw material reward is named `Elements` in journal, when on startup the collection of Raw mats is named `Raw`
Bugfix proposal/POC
I turned in a few Raw mats rewards
> Fixes #2360: Translate Elements MaterialReward as Raw

- monitor.py
- plugins/inara.py
Adds more Powerplay rank/merit tracking using the new journal entries
Enhancement
Ran the code with changes and monitored my Inara to see the changes reflected.
This is a followup to my last Powerplay PR that added tracking in the first place. I think we're okay to catch these specific events as they only concern individual commanders. The overall state of a system is covered in other location events.
> Update powerplay tracking to account for new journal events

- resources/EDMC_Installer_Config_template.txt
This PR removes the PowerShell check in the Inno Setup installer, which checks for previous versions of EDMC that used the WiX setup via MSI compared to the current "Inno Setup"-powered exe files. EDMC has used Inno since 5.9.1 (over a year and a half ago). 
The vast majority of users (over 99%) have already updated to a version later than 5.9.0. Any user still on those versions is likely intentionally holding to that version. Any user on those versions would need to manually remove the old version, but the installer wouldn't hand-hold them anymore. 
For most users, this will greatly improve the speed of the installer and can fix some side issues if a user has a very restricted PowerShell permission set. This will also reduce the chance of an AV engine flagging for anomalous PowerShell. …
> [#2348] Remove WiX Check

- EDMarketConnector.py
- L10n/en.template
- prefs.py
This PR adds the ability to optionally disable the Systray on Windows. When disabled, this will also prevent the program from minimizing to systray. When modifying this setting, EDMC will automatically enforce a restart. 
Additionally, this adds a number of new options to the right-click menu for the systray when enabled.
Finally, this fixes a typo in earlier code comments. 
Enhancement
Tested with various permutation settings to ensure that modifying the setting will have desired effects and does not lock the program. 
Closes #1346
> [#1346] Option to Disable Systray

- EDMC.py
This PR adds an option to the EDMC command line to iterate over all known CMDRs and poke CAPI to keep the access and token live. This will reduce the number of re-authorizations that users need to perform if they make this a scheduled action. 
Enhancement
Tested with various permutations of working tokens, invalid tokens, expired tokens, etc across 3 CMDRs.
Resolves #579
> [579] Add EDMC CMDR Iteration

- config/linux.py
- config/windows.py
- coriolis-update-files.py
- edshipyard.py
- hotkey/linux.py
- hotkey/windows.py
- killswitch.py
- l10n.py
- monitor.py
- outfitting.py
- plug.py
- protocol.py
- scripts/find_localised_strings.py
- shipyard.py
- theme.py
This PR removes the `assert` statement from EDMC non-test code where present, paving the way to enable -OO code. Assert is not really a good idea to use in live code, and should not be used outside of tests and debugging. This PR attempts to cleanly hand over all assert and assert-like statements to other exception types. 
Resolves #1287. Related to #1775.
> [#1775] Retire Usage of Assert

- EDMarketConnector.py
- common_utils.py
- hotkey/windows.py
- l10n.py
- prefs.py
- protocol.py
This PR hands off more ctype calls to pywin32, which helps ensure more pythonic, error-safe, and simpler code can be used instead of home-rolling our own code for interacting with the Windows API. Additionally, this fixes a bug in the Hotkeys module which broke a segment of the hotkey functionality on Windows hosts. 
* Removes a dependency on windll and ctypes.create_unicode_buffer in EDMarketConnector.py
* Removes a duplicate check for CalculatePopupWindowPosition in favor of pywin32's win32api.MonitorFromWindow in common_utils.py. 
* Completely revamps the hotkey module for Windows to use pywin32 code.
* Removes some unused l10n.py ctypes calls that were not used anywhere
* Improves the language selection to utilize locale and pywin32 on Windows
* Removes some unused code from prefs.py …
> [#1805/#2389] Fix Hotkey and Reduce Ctypes

- L10n/tr.strings
- l10n.py
- modules.json
- ships.json
This PR restores a simplified and logic-enhanced version of the CTYPES Localization Check for Windows. 
The version of the localization system for Windows implemented in 5.13.0 broke edge cases where the user's localization was not a traditional English speaking location, but the user had set their system to English. (See: en-nl) This caused an error as en-nl could not be matched in Python's localization module. This edge case was missed by the Beta. 
The CTypes legacy detection has been re-implemented, but with fewer defined ctypes declarations for a smoother experience. 
Bugfix
Legacy code reimplementation, tested with different forced detection of languages. 
Fixes #2433
Fixes #2431
> [2431] Reimplement Ctypes LongLang Check
