PLUGINS.md

Add instructions for how to include dependencies in plugin.

---

eddn.py

Really bad salt to reduce the possibility for looking up commander names with online md5 dycrypters. Also reference to current Salt Harvester number 1.

Terrible Salting Technique

---

plugins/inara.py

"Inara setCommanderReputationMinorFaction, The reputation value exceeds the valid range"

Fixing reputation values error on Inara

---

EDMarketConnector.py
plug.py

Use the after method of root to open the messagebox inside the mainloop (fixes #522).

Bugfix #522

---

EDMarketConnector.wxs
L10n/sv-SE.strings

TODO: Add to installer setup so it will be in the next release.
See issue #529 for checklist to ensure this makes it into next beta release.

Add Swedish Translationo

---

commodity.py

I removed most of the overly complex oneliners for equivalent multi-line
constructs. The code behaviour should remain the same.
Otherwise mostly reformatting happened here, spaces after commas, that
sort of thing.

Cleanup commodity.py (PEP8, code simplification)

---

theme.py

'dpy' needs to be global, and there might be other side effects.  So just revert to this code being global.

Pull X11 setup back out of function for 'dpy'.

---

companion.py

Code cleanup and PEP8 compatibility.

Cleanup companion.py

---

commodity.py

Remove last traces of 'BPC' output code

---

edshipyard.py

Standard treatment, newlines around scope changes, removed tabbed inline comments, replaced modulo formatting with .format formatting, replaced overcomplex oneliners

cleanup edshipyard

---

ChangeLog.md
config.py
edmarketconnector.xml
plugins/eddb.py

Fixex the EDDB System URL issue with CAPI lastSystem->id sometimes being bogus.

Release 4.0.1.0

---

Contributing.md
docs/Releasing.md

Added linting, testing, and new requirements-dev.txt instructions

Updated docs

---

.github/ISSUE_TEMPLATE/enhancement.md

Create Enhancement issue template

---

monitor.py

Fix ~ not being expanded on linux

---

docs/Releasing.md

Need to keep 'Known Issues' up to date.

Releasing.md: Update 'Known Issues' after a stable release.

---

EDMC.py

Step 1 in getting this testable will be a cleanup, after that breaking out into functions that can be mocked etc. So far this just contains step 1

Cleanup EDMC

---

.flake8
.github/workflows/pr-annotate-with-flake8.yml
.github/workflows/push-checks.yml
requirements-dev.txt

Testing pr-annotate-flake8

---

plugins/eddb.py

Usual string of PEP8 and readability improvements

Cleanup eddb plugin

---

plugins/inara.py

I missed some print based debugging in the previous PR, this removes some and replaces others with logger based logs

Added debug logs for inara 

---

.github/workflows/pr-annotate-with-flake8.yml
.github/workflows/pr-checks.yml
.github/workflows/push-checks.yml
EDMC.py

It only works with sufficient access anyway.

Try to only run flake8 annotate on Athanasius' PRs

---

EDMCLogging.py
EDMarketConnector.py

The code in caller_class_and_qualname() now handles a bare function in a file as the caller.

logging: support bare functions

---

PLUGINS.md

* Currently you use `print(...)`
* `logging` support is coming, here's how to prepare.

PLUGINS.md: Logging is being added, how to prepare

---

.github/workflows/pr-annotate-with-flake8.yml
EDMCLogging.py

The annotations can only be added if the branch is in the same repo.
Easiest fix is likely to check if the base and head reference the same repo.
Alternative is to actually try to add an annotation as a check.

flake8-your-pr annotations fail for any fork branch

---

plugins/inara.py

Standard pep8 treatment et al.
Still considering replacing all OrderedDicts with simple dicts.

Cleanup inara.py

---

companion.py

Although #679 turned out to be a Frontier issue we would benefit from extra logging so we can see the state of things and which code paths a user goes through if having CAPI/auth issues.

companion.py: Add more logging to better trace auth/CAPI flow

---

.flake8
.github/workflows/pr-checks.yml
Contributing.md
requirements-dev.txt

Specifically this swaps out the format string plugins to one that prefers fstrings over `%` and `.format`, and adds a docstring plugin (explicitly disabled in PRs)
I also cleaned up Contributing.md a little

Add more flake8 plugins

---

EDMarketConnector.py
L10n/en.template
prefs.py

Hopefully this version will work for everyone.

Change UI tk.Scale() to use integers to avoid locale issues.

---

EDMarketConnector.py

As we might run into some special cases with users we need to log in more detail what the locale is around our changes.
NB: Also contains some misc. PyCharm-enacted formatting changes, white space, wrapping etc.

Locale: More detailed login at startup around changes

---

plugins/edsm.py

We've had a report of EDSM not picking up CarrierJump properly.  So let's have some extra logging to check and help diagnose.

Add detailed logging of Carrier/FSDJump to edsm plugin

---

prefs.py

Breaks the init up into multiple methods, passes flake8 with some minor warnings.

Cleanup prefs.py

---

plugins/inara.py

This brings inara in line with our more recent linter changes.

Continued inara cleanup

---

PLUGINS.md
docs/examples/click_counter/load.py

Removed some of the weird choices in the code blocks, cleaned up markdown, added example plugin.

Add example plugin and clean up plugin docs

---

EDMarketConnector.py
companion.py
monitor.py
plug.py
plugins/edsm.py

Some useful output is hidden behind `__debug__`.  Also some of it should be INFO anyway.
Draft as I work on this.

Change monitor.py to use logging, not `__debug__` & print

---

.mypy.ini
.pre-commit-config.yaml
EDMC.py
EDMCLogging.py
EDMarketConnector - TRACE.bat
EDMarketConnector.py
companion.py
monitor.py
plug.py
plugins/edsm.py
prefs.py

We'll sometimes want detailed logging to trace down a bug, but don't want to always spam DEBUG level.
1. Defines logging.TRACE as 5.
1. Adds the string "TRACE" to match it.
1. Adds a new trace() method to log at this level.
1. Adds a CL arg on EDMarketConnector to set this.
Need to address EDMC.py as well.

Implement a TRACE level of logging

---

EDMarketConnector.py

Simple change, hardly even needs a review, but could stand a bit more testing to be sure.
Addresses #725

Locale: Use LC_CTYPE as source of language for setting UTF-8 encoding

---

plugins/edsm.py

I don't think I changed the flow at all here, but the logging is more detailed.
Surely previously it only logged non-1XX individual events if they weren't `in ('StartUp', 'Location', 'FSDJump', 'CarrierJump')`, and thus a non-1XX on any of those would never have been logged ?

EDSM: Finer-grained and more detailed logging of API results

---

.pre-commit-config.yaml
config.py

The intent is to pass flake8 and mypy tests.

Cleanup of config.py

---

EDMarketConnector.py

We have at least one instance of not starting on Windows 7 still, see #755

Locale: Be even more paranoid about setting UTF-8 encoding

---

EDMCLogging.py
EDMarketConnector.py
dashboard.py
hotkey.py
monitor.py
plugins/eddn.py
plugins/edsm.py
plugins/inara.py
protocol.py

The branch name is because of ensuring we notify the user when shutting down.  This will also now change the status text to 'Shutdown down...' and *not* 'withdraw' the window in the meantime.
Also adding more logging to startup so we have at least one logged line recording thread id.

Add detailed logging to shutdown code

---

companion.py
plugins/eddb.py
plugins/eddn.py
plugins/edsm.py
plugins/inara.py

CAPIData is a dict that we control, it will be replaced later with a more specific object that can be type checked.

Add CAPIData object 

---

commodity.csv

Fixed Void Opal name in commodities.csv

---

.github/workflows/windows-build.yml

This should make it show up with a more sane name

Add name to windows build action

---

.github/workflows/push-checks.yml

Also makes sure that pushes to main ARE checked

Replace python checks with jq in workflow

---

EDMC.py
config.py
dashboard.py
l10n.py
monitor.py
plug.py
plugins/eddn.py
prefs.py

This is mostly a quick fixup. Most of these could probably be done using pathlib features instead (and there are a few joins to fix as well). But I want `develop` to WORK first.

Add _str variants of config.$DirNameHere for any string ops that may be needed

---

PLUGINS.md

Just some minor mistakes in the docs I happened to stumble upon.

PLUGINS.md: fix typo & example for `journal_entry`

---

EDMarketConnector.py
config.py
constants.py
protocol.py

This adds support for a `--suppress-dupe-process-popup` CL arg to address #848 
This version is against `main`, once it's merged I'll sort out `develop` separately.

Add --suppress-dupe-process-popup and move enforce_single_instance() call after

---

protocol.py

Also worked out what exactly that windows DDE code does and threw a wall of comments at it
Draft because untested

Cleanup protocol.py

---

companion.py
hotkey.py
l10n.py
monitor.py
plugins/eddn.py
plugins/edsm.py

Small fixups for various `-W default` output.  I'll need https://github.com/EDCD/EDMarketConnector/pull/762 merged to be able test test more code for this, so WIP.

Fix/735 address -W default output

---

PLUGINS.md
monitor.py

This still needs documentation adding in PLUGINS.md, which is easiest done after #897 is merged and re-based upon.

Add support for ModuleInfo event and file contents. 

---

.pre-commit-config.yaml
monitor.py

Without making major code changes the aim is to get nothing flagged by flake8 or mypy.

monitor.py: General cleanup work on flake8 & mypy output

---

config.py
monitor.py
tests/test_config.py

Also a tiny comment only fix to make mypy happy

Add more logging to getint and get methods

---

EDMarketConnector.py
companion.py
protocol.py

Attempting to track down what's going on with #909

Add extra logging for Frontier Auth, especially via edmc://

---

plugins/eddn.py

The .values() is on this, so it also needs to be a dict.
I also made the logging of "FC or Damaged Station?" consistent
throughout this file.
Yes, we'll keep these as logger.debug() for now.

Extend is_horizons() paranoia to type of ships['shipyard_list']

---

.gitignore
EDMC.py
EDMarketConnector.py
EDMarketConnector.wxs
companion.py
config.py
constants.py
killswitch.py
plugins/eddn.py
plugins/edsm.py
plugins/inara.py
prefs.py
setup.py
td.py
update.py

The idea here is that we can be sure that a version number such as '5.0.0-beta1' is either an actual release with that version or instead is someone running from source where appversion hasn't been changed.

Show git HEAD short hash as part of version

---

plugins/eddn.py

This also includes a change from the hacky `this` to a class-based one.

plugins/eddn: Now fully docstring'ed.

---

EDMarketConnector.py

Surprisingly window_title has nice simple types.

EDMarketConnector.py: Two missing type annotations

---

PLUGINS.md
config.py
docs/examples/plugintest/load.py
killswitch.py
update.py

* Converted to the class `this`.
* Added example of checking core EDMC version.

plugintest: Some cleanup and example core version test

---

config.py

* Also updates coriolis-data to what I pulled for 5.0.0 so `git status` isn't always noting it.  I have *not* generated new .p files from it for this branch.

config.py: Compatibility layer for newer API calls.

---

monitor.py

1. It's JournalAlpha.<etc>.log for the file name.
2. They contain a gameversion which contains 'alpha', which we detect to set is_beta = True.

Use Odyssya JournalAlpha files

---

PLUGINS.md
monitor.py

Tested by replaying the affected Journal files.

monitor.py: Add support for Odyssey 'Component' materials.

---

outfitting.py
protocol.py

This also includes a small protocol.py tweak, to silence extraneous INFO logging if run without UI (EDMC.py).

outfitting.py: Cleanup flake8 and mypy output

---

companion.py

mypy is still a PITA with `Optional[<type>]` thinking the variable is `None` at points and refusing to believe it has methods the non-None type has.

companion.py: Fix lints

---

hotkey.py

Had to rework into an Abstract class with platform-specific implementations.
Works on win32 without darwin/linux code causing issues, and likewise on Linux without win32/darwin causing issues.

hotkey.py: General lint cleanup

---

L10n/en.template
companion.py

* Generic 'Error'.
* Strings for Access Token customer_id != FID.
* Other strings in companion.py now translating.
* Missing colon on Plugins string.

translations: Re-order as per l10n.py output & some added

---

.gitignore
EDMarketConnector.py
L10n/en.template
PLUGINS.md
companion.py
edmc_data.py
monitor.py

There's no way to get any of this from the Journal currently, so it comes from CAPI.
We should be able to use some Journal events to then update the current suit in UI though.

Add support for Odyssey Suit/Loadout data

---

EDMarketConnector.py
L10n/en.template
prefs.py
requirements.txt

Closes #126 
This PR adds a preference option and implementation using `infi.systray` package. There are a few hacks here and there and translation for the new option is not done.
Starting with the PR to get feedback.

EDMarketConnector: Added minimize to tray on close functionality

---

PLUGINS.md
companion.py
monitor.py

Alpha4 has augmented Suit related events with extra data, so use it.

Odyssey Alpha4 extra suits-related support

---

EDMarketConnector.py
monitor.py
plugins/eddb.py
plugins/edsm.py
plugins/inara.py

1. Docking in a taxi is before CAPI location is updated, but it is for Disembark.

Misc fixes for Odyssey

---

monitor.py

See the comment added to BookDropship code for why we're ignoring it.

Set OnFoot for DropshipDeploy, but ignore BookDropship

---

monitor.py

MissionCompleted doesn't contain 'Reward' if you pick an option without a credits amount (rather than being there but with zero value).
Let's not wait to find out about other exceptions, just utilise entry.get(<field>, 0) on them all.

Credits: Be paranoid about all related Journal events

---

EDMCLogging.py
tests/EDMCLogging.py/test_logging_classvar.py

Also adds a wall of logging if ever again an exception is thrown in this code.

Fix classvar logging errors

---

EDMarketConnector.py
edmc_data.py
monitor.py

Some adjustments to Odyssey inventory and Suit/Loadouts event processing as outlined in Journal v31 changes.
Untested, need to get in-game on live Odyssey to be sure any of it is correct and works.

Adjust Odyssey support re: Journal v31

---

config.py

Show whether or not the git wdir is dirty in version

---

monitor.py

Update credits on UpgradeSuit

---

monitor.py
plugins/inara.py

This is an example of just how icky it gets validating an event by hand.
Technically we need a function, many would probably be lengthier andmore complex than this one, for **every   single   journal   event  type**.

EngineerProgress: Extra validation paranoia

---

L10n/en.template
companion.py

Mostly call out this is 'Frontier CAPI' related.

CAPI: Make user-visible error text more obvious

---

stats.py

Closes #1060 
Currently theres no way to copy entire lines or pages as that would require more storage than currently exists.

Add the ability to copy entries from the status page

---

monitor.py

This is mostly because I brainfarted after a copy/paste, not editing down the code from the 'array' version.
Closes #1111

EngineerProgress: Progress can be for a single engineer, no array

---

monitor.py

This updates our TransferMicroResources handler with the changes from
v4.0.0.200, and BackPack handler to also handle Backpack as the event
name.
Additionally Fixed various events
(CollectItems, DropItems, TransferMicroResources)
doubling up BackpackChange work, thus causing offset counts.
Fixes #1115

Update MicroResource tracking for gameversion 4.0.0.200

---

EDMC.py
EDMarketConnector.py
companion.py
plug.py
plugins/edsm.py
setup.py
td.py
theme.py

closes EDCD/EDMarketConnector#569

Cleanup imports where possible, remove incase imports

---

plugins/edsm.py

EDSM: Don't blindly assume we *already* have EDSM cmdr name and apikey

---

monitor.py

closes EDCD/EDMarketConnector#1138

Fixed erroring on empty backpack.json

---

Contributing.md

Also fixes header levels after 'Scope changes'.

Contributing: Add section on choosing the correct logging level

---

Contributing.md
EDMarketConnector.py
scripts/find_localised_strings.py
stats.py

This could probably benefit from:
- deduping (at least for some output options)
- the ability to direct compare with the existing template file

Added AST based LANG translation string detection

---

Contributing.md
docs/Translations.md

What started as "that LANG bit should be in Translations.md" turned into a general review.

General Contributing.md and Language.md cleanup/reformat

---

.pre-commit-config.yaml
EDMarketConnector.py
L10n/en.template
l10n.py
plugins/coriolis.py
plugins/eddn.py
plugins/edsm.py
plugins/inara.py
prefs.py
scripts/find_localised_strings.py
theme.py
ttkHyperlinkLabel.py

This includes some fixes to the new script, along with at least one definite translations string change.
Draft until I've done the full pass on all existing translations.

Translations: General cleanup pass

---

EDMC.py
EDMarketConnector.py
companion.py
journal_lock.py
plugins/coriolis.py
plugins/eddb.py
plugins/eddn.py
plugins/edsm.py
plugins/inara.py
prefs.py
scripts/find_localised_strings.py
stats.py

We'll be relying on the new l10n script, so ensure *all* necessary LANG comments are in place.

Add all missing LANG comments

---

monitor.py

New version of #1089 - rebased on `develop` and then newer code converted as well.
Closes #1087

Made most event lookups case insensitive

---

config.py

closes EDCD/EDMarketconnector#967

Cache appversion when it is created

---

companion.py

Strip the extra + chars in surface port names that are wrongly returned by the CAPI.
Also rely on station ID checks rather than name comparison before we assume the CAPI is lagging

re #1198 work around +size suffixes in CAPI responses

---

monitor.py

monitor: Retry on ShipLocker.json load/decode failure

---

EDMarketConnector.py
L10n/en.template
prefs.py

Add options to hide private group name and multicrew commander name from UI

---

config.py

Fixed get_bool on windows not returning defaults in some cases

---

Contributing.md
EDMC.py
EDMCLogging.py
EDMarketConnector.py
companion.py
journal_lock.py
monitor.py
plug.py
plugins/eddn.py
plugins/edsm.py
protocol.py

`--trace-on ...` rocks, so let's use it everywhere, with possibly a few exceptions.

Convert all/most `logger.trace(...)` to `logger.trace_if(...)`

---

prefs.py

Output > 'File Location' should always be available

---

docs/Killswitches.md
scripts/killswitch_test.py

(also a tiny bugfix in the test script)

Additional example for killswitch docs

---

Contributing.md
EDMC.py
EDMarketConnector.py
L10n/en.template
companion.py
loadout.py
plugins/eddn.py
stats.py

Basic tests of both the GUI app and EDMC.py show this as working.

Change all CAPI queries over to a queue/thread model

---

EDMarketConnector.py

This is the hacky version of #1283

hack to fix --force-localserver-auth

---

EDMarketConnector.py

Just a simple addon of a few config resets.
This likely needs a test as I have not yet done so.
closes EDCD/EDMarketConnector#1155

Reset geometry and UI scale with --reset-ui

---

EDMCLogging.py

Draft because there are some questions of format involved

Switch logging times to be in UTC

---

plugins/inara.py

inara: Utilise Statistics Current_Wealth for commanderAssets

---

L10n/en.template
stats.py

Also adds a tiny bit of spacing between regular ranks and powerplay stuff.
closes #1369

Add Odyssey ranks to status page

---

monitor.py

Navroute parsing can fail due to racy writes if we're too quick. 
This PR solves this by trying on the 10 subsequent events after a NavRoute.

Retry parsing navroute after failure

---

monitor.py

We can't just use `EDLogs.live` here as it'll get set `true` when the `Commander` event is seen *during the catch up*.  We need that catchup to have finished before we'll try processing a `NavRoute` event and file.

monitor: Gate navroute on *not* being in journal catch up mode

---

plugins/inara.py

Now based on the *minimum* of a fractional or absolute change.
Closing #1255

Inara: Change the way we determine if a credits delta is interesting

---

monitor.py

See the comments in #1395 for why this should be sufficient to fix the bug.

monitor: Fold 'EngineerCraft' to lower case in event_type comparison

---

.pre-commit-config.yaml
monitor.py
plugins/eddn.py

Closing #1450 
This did end up touching some other code.  ~~I should probably double-check my new `monitor.state` stuff is always properly initialised.~~ Already did.

eddn: approachsettlement/1 implementation

---

requirements-dev.txt
requirements.txt

NB: This can't be merged until there's a 0.11.1.0 release of py2exe.

windows-build: Try out pre-release py2exe w/ semantic_version==2.9.0

---

plugins/eddn.py

The game just has to be awkward about the order of things....
Closing #1482

EDDN: approachsettlement/1: Bail if no System (name) yet

---

monitor.py

Using os.path.getctime for the order, not the filename.  This addresses the changed Journal filenames in Odyssey Update 11, whilst keeping compatibility with the Horizons Update 11 old-name-style filenames.
Closing #1504

Fix 'newest journal file' determination for Odyssey Update 11

---

plugins/eddn.py

EDDN: Add support for new schema `fssbodysignals`

---

plugins/eddn.py

Closes #1557 
Add cross-checks to all the location augmentations.  This should work around any game bugs with not always seeing all of the relevent events.

eddn: Location augmentations cross-check paranoia

---

monitor.py

Implement parsing the new (Odyssey Update 12 / 4.0.0.1300) `FCMaterials.json` file, which lists the materials trades available at a Fleet Carrier bar tender.
I don't see any reason to store this in `monitor.state` as it's somewhat ephemeral, we'd need to remove it again on Embark.
Untested, because the game update isn't released yet.
Closes #1567

Journal: FCMaterials: Implement parsing separate file

---

EDMarketConnector.py

Be paranoid about Frontier possibly supplying erroneous data.
Closes #1572

CAPI: Check if lastStarport->id matches Journal MarketID

---

wix/template.wxs

This doesn't cause any issues with our installer build, but I've not yet tested the resulting installer.
Specifically I've not tested that it *does* solve the issue.
Closes #1492

Attempt to address unprompted reboots from installer

---

plugins/eddn.py

eddn/fsssignaldiscovered: Catch where no signals pass checks

---

monitor.py
plugins/inara.py

inara: Send only Live galaxy data after Update 14

---

plugins/inara.py

Only warn about Inara/Live data only if configured to send on Legacy.

---

plugins/inara.py

Addresses #1732 specifically.
At some point #1433 needs fully addressing (review all Inara API code for compliance with docs).

Inara: Drop various combat messages if empty opponentName

---

.mypy.ini
.pre-commit-config.yaml
EDMarketConnector.py
PLUGINS.md
companion.py
docs/Killswitches.md
killswitch.py
plugins/eddn.py

Implement killswitch functionality for CAPI data retrieval and use as per #1714

companion: A start on adding CAPI killswitches

---

EDMC.py
L10n/en.template
update.py

Adds a new translation string option for the New Release status message.
- Adds  new translation option
Closes #2140

[2140] Translate Newver Str

---

plugins/eddn.py

Adds the stationType and carrierDockingAccess values to EDDN Commodities Journal Data when known. While this isn't called in all circumstances, this is the location in which this data is known. We will be revisiting the priority of sending this data, but for now, add the data when known if this function is called.
- Minor Change
Closes #2157

[#2157] Add Station and Docking Data When Known

---

.github/SECURITY.md
.github/pull_request_template.md
.github/workflows/codeql.yml

This PR adds a security template to the repository, informing users how to securely disclose security vulnerabilities to us (as per the [Community Standards](https://github.com/EDCD/EDMarketConnector/community).
This also adds a standard PR template to ensure uniformity across PR branches. 
Finally, this PR adds a CodeQL static code analysis scanner. 
- Documentation and Workflow Updates

[Docs] Add CodeQL Workflow and Security Guide

---

edshipyard.py
modules.json

Adds more Python Mk II modules and the Coriolis information of the new SCO Modules (See https://github.com/EDCD/coriolis-data/pull/98). Reverts a spelling change in edshipyard pending further review of that function (Is consumed by 3rd parties so likely 6.0 change.)
Bug Fix/Module Addition
Tested with builds and with third-party tools such as TCE.
Resolves #2228

[2228] Add SCO Modules and Preliminary Python Mk II Support

---

.github/workflows/push-checks.yml
scripts/find_localised_strings.py

This PR adds a check to pushes to ensure that there are no missing translations, unused translations, or other out-of-date strings in the translation system. This check runs on every push. 
Feature Enhancement
Tested by breaking and fixing translations and testing output on pushes in a test branch. And screaming at bash. Lots of screaming at bash. See: 
https://github.com/HullSeals/EDMarketConnector/actions/runs/9278648668/job/25529983265
https://github.com/HullSeals/EDMarketConnector/actions/runs/9278611138/job/25529891228
Resolves #1469

[#1469] Add Translation Push Check

---

EDMCLogging.py
EDMarketConnector.py
collate.py
companion.py
plug.py
prefs.py
update.py

This PR adds a sanity check to the WinSparkle updater. The updater will throw a GUI or console error when an exception is encountered in the init function of WinSparkle. 
Additionally, multiple if-else statements are changed to ternary operators.
Enhancement
Tested by intentionally throwing errors in the updater section and ensuring a GUI popup is shown.
Resolves #1822

[1822] Update Check Catch

---

EDMC.py
EDMCLogging.py
EDMCSystemProfiler.py
EDMarketConnector.py
PLUGINS.md
build.py
common_utils.py
plugins/common_coreutils.py
plugins/coriolis.py
plugins/eddn.py
plugins/edsm.py
plugins/edsy.py
plugins/inara.py
plugins/spansh_core.py
prefs.py
scripts/find_localised_strings.py
stats.py

This PR attempts to unify common elements of EDMC code in the core program and in plugins. The intent of this is to reduce the number of duplicate code entires to ensure a more maintainable, pythonic code base. This is performed by creating a new plugin (core-utils) and a new common_utils function to handle these duplicate entries. 
This plugin also removes an unused code function in edmc.py which has not been called by anything for ~5 years and minor edits to improve code readability. 
Enhancement
Tested with both EDMC.py, EDMarketConnector.py, and built versions (.exe) to ensure that the code is functioning as intended in frozen and unfrozen states. 
Resolves #2406

[#2406] Duplicate Code Refactor

---

plugins/eddn.py

This PR endeavors to fix the edge case that occurs when a legacy replay.jsonl file exists in a user's directory and has not been removed, and the replay file has a missing delimeter. This can cause the EDDN module to crash, as it prevents the eddn module from loading. 
This PR adds the following checks: 
- Uses Pathlib's Path.exists() module instead of relying on FileNotFound errors
- Reduces privilege of context manager from r+ to r. 
- Removes redundant truncation before file removal
- Enhances error handling to log and record errors while not crashing the plugin
- Hands over the open and unlink modules from os to pathlib.
Given that this system is a legacy handover from 5.6.0, this should be removed in 6.0 and is now marked deprecated.
Bugfix
Tested by placing an intentionally …

[#2375] Improve Legacy Queue Detection
